// <auto-generated />
using System;
using Elsa.Secrets.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.Secrets.Persistence.EFCore.MySql.Migrations.Secrets
{
    [DbContext(typeof(SecretsElsaDbContext))]
    partial class SecretsElsaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Elsa")
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Elsa.Secrets.Models.Secret", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SerializedTags")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tags");

                    b.Property<string>("SerializedVersions")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Versions");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Secret_Name");

                    b.HasIndex("Scope")
                        .HasDatabaseName("IX_Secret_Scope");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Secret_Status");

                    b.HasIndex("StoreName")
                        .HasDatabaseName("IX_Secret_StoreName");

                    b.HasIndex("TypeName")
                        .HasDatabaseName("IX_Secret_TypeName");

                    b.ToTable("Secrets", "Elsa");
                });
#pragma warning restore 612, 618
        }
    }
}
