<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            Provides integrations with an Orchard Core application instances through activities and via HTTP.
        </Description>
        <PackageTags>elsa extension module orchardcore</PackageTags>
    </PropertyGroup>

    <ItemGroup Label="Elsa" Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\..\..\..\..\elsa-core\src\modules\Elsa.Http\Elsa.Http.csproj" />
        <ProjectReference Include="..\..\..\..\..\elsa-core\src\modules\Elsa.Http.Webhooks\Elsa.Http.Webhooks.csproj" />
    </ItemGroup>

    <ItemGroup Label="Elsa" Condition="'$(UseProjectReferences)' != 'true'">
        <PackageReference Include="Elsa.Http" />
        <PackageReference Include="Elsa.Http.Webhooks" />
    </ItemGroup>
    
</Project>
