<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AngleSharp" />
        <PackageReference Include="bunit" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\..\testing\BunitTestDefaults.cs" Link="BunitTestDefaults.cs" />
        <Compile Include="..\..\testing\MenuPopoverAssert.cs" Link="MenuPopoverAssert.cs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Elsa.Studio.Environments/Elsa.Studio.Environments.csproj" />
        <ProjectReference Include="../Elsa.Studio.Authentication.ElsaIdentity.BlazorServer/Elsa.Studio.Authentication.ElsaIdentity.BlazorServer.csproj" />
        <ProjectReference Include="../../framework/Elsa.Studio.Core.BlazorServer/Elsa.Studio.Core.BlazorServer.csproj" />
        <ProjectReference Include="../Elsa.Studio.Security/Elsa.Studio.Security.csproj" />
    </ItemGroup>

</Project>
