using Elsa.Mqtt.Options;

namespace Elsa.Mqtt.UnitTests.Options;

public class MqttConnectionOptionsTests
{
    // ---------- ClientId ----------

    [Fact]
    public void GenerateMqttClientOptions_UsesProvidedClientId()
    {
        var options = new MqttConnectionOptions { Host = "localhost", Port = 1883, ClientId = "my-client" };

        var result = options.GenerateMqttClientOptions();

        Assert.Equal("my-client", result.ClientId);
    }

    [Fact]
    public void GenerateMqttClientOptions_AutoGeneratesClientId_WhenClientIdIsNull()
    {
        var options = new MqttConnectionOptions { Host = "localhost", Port = 1883 };

        var result = options.GenerateMqttClientOptions();

        Assert.NotNull(result.ClientId);
        Assert.StartsWith("Elsa", result.ClientId);
    }

    [Fact]
    public void GenerateMqttClientOptions_AutoGeneratedClientIds_AreUnique()
    {
        var options = new MqttConnectionOptions { Host = "localhost", Port = 1883 };

        var id1 = options.GenerateMqttClientOptions().ClientId;
        var id2 = options.GenerateMqttClientOptions().ClientId;

        Assert.NotEqual(id1, id2);
    }

    // ---------- Credentials ----------

    [Fact]
    public void GenerateMqttClientOptions_SetsCredentials_WhenUsernameAndPasswordProvided()
    {
        var options = new MqttConnectionOptions
        {
            Host = "localhost", Port = 1883,
            Username = "user", Password = "secret"
        };

        var result = options.GenerateMqttClientOptions();

        Assert.NotNull(result.Credentials);
    }

    [Fact]
    public void GenerateMqttClientOptions_SetsCredentials_WhenOnlyUsernameProvided()
    {
        var options = new MqttConnectionOptions
        {
            Host = "localhost", Port = 1883,
            Username = "user"
        };

        var result = options.GenerateMqttClientOptions();

        Assert.NotNull(result.Credentials);
    }

    [Fact]
    public void GenerateMqttClientOptions_DoesNotSetCredentials_WhenUsernameAndPasswordAreAbsent()
    {
        var options = new MqttConnectionOptions { Host = "localhost", Port = 1883 };

        var result = options.GenerateMqttClientOptions();

        Assert.Null(result.Credentials);
    }

    [Fact]
    public void GenerateMqttClientOptions_DoesNotSetCredentials_WhenOnlyPasswordProvided()
    {
        // The implementation guards with !string.IsNullOrEmpty(Username), so password-only
        // should not attach credentials.
        var options = new MqttConnectionOptions
        {
            Host = "localhost", Port = 1883,
            Password = "secret"
        };

        var result = options.GenerateMqttClientOptions();

        Assert.Null(result.Credentials);
    }

    // ---------- TLS ----------

    [Fact]
    public void GenerateMqttClientOptions_BuildsSuccessfully_WhenUseTlsIsTrue()
    {
        var options = new MqttConnectionOptions { Host = "localhost", Port = 8883, UseTls = true };

        // Should not throw; TLS enabled without a client cert is a valid configuration.
        var result = options.GenerateMqttClientOptions();

        Assert.NotNull(result);
    }

    [Fact]
    public void GenerateMqttClientOptions_BuildsSuccessfully_WhenUseTlsIsFalse()
    {
        var options = new MqttConnectionOptions { Host = "localhost", Port = 1883, UseTls = false };

        var result = options.GenerateMqttClientOptions();

        Assert.NotNull(result);
    }

    [Fact]
    public void GenerateMqttClientOptions_BuildsSuccessfully_WhenAllowUntrustedCertificatesIsTrue()
    {
        var options = new MqttConnectionOptions
        {
            Host = "localhost", Port = 8883,
            UseTls = true,
            AllowUntrustedCertificates = true
        };

        // Should not throw.
        var result = options.GenerateMqttClientOptions();

        Assert.NotNull(result);
    }

    [Fact]
    public void GenerateMqttClientOptions_Throws_WhenClientCertificatePathDoesNotExist()
    {
        var options = new MqttConnectionOptions
        {
            Host = "localhost", Port = 8883,
            UseTls = true,
            ClientCertificatePath = "non-existent-cert.pfx"
        };

        Assert.ThrowsAny<Exception>(() => options.GenerateMqttClientOptions());
    }

    // ---------- General ----------

    [Fact]
    public void GenerateMqttClientOptions_ReturnsNonNullOptions()
    {
        var options = new MqttConnectionOptions { Host = "localhost", Port = 1883 };

        var result = options.GenerateMqttClientOptions();

        Assert.NotNull(result);
    }
}
