using System.Reflection;
using Elsa.Abstractions;
using FastEndpoints;
using JetBrains.Annotations;

namespace Elsa.Workflows.Api.Endpoints.Package;

/// <inheritdoc />
public class GetVersion : Endpoint<Request, Response>
{
    /// <inheritdoc />
    public override void Configure()
    {
        Get("/package/version");
    }

    /// <inheritdoc />
    public override async Task HandleAsync(Request request, CancellationToken cancellationToken)
    {
        var assembly = Assembly.GetExecutingAssembly();
        var versionAttribute = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
        var version = RemoveAutoGeneratedPostfix(versionAttribute);

        await SendOkAsync(new Response(version), cancellationToken);
    }

    private static string RemoveAutoGeneratedPostfix(AssemblyInformationalVersionAttribute? versionAttribute) =>
        versionAttribute?.InformationalVersion.Split("+")[0]!;
}