<Project>

    <Import Project="../../../Directory.Build.props" />

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>false</IsTestProject>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
