<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../src/modules/Elsa.Http/Elsa.Http.csproj" />
        <ProjectReference Include="../../../src/modules/Elsa.Scheduling/Elsa.Scheduling.csproj" />
        <ProjectReference Include="../../../src/modules/Elsa.Tenants.AspNetCore/Elsa.Tenants.AspNetCore.csproj" />
        <ProjectReference Include="../../../src/modules/Elsa.Workflows.Api/Elsa.Workflows.Api.csproj" />
        <ProjectReference Include="../../../src/modules/Elsa.Workflows.Runtime.Distributed/Elsa.Workflows.Runtime.Distributed.csproj" />
        <ProjectReference Include="../../../src/modules/Elsa/Elsa.csproj" />
    </ItemGroup>

</Project>
