<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../src/modules/Elsa/Elsa.csproj" />
        <ProjectReference Include="../../../../src/common/Elsa.Features/Elsa.Features.csproj" />
        <ProjectReference Include="../../../../src/modules/Elsa.Http/Elsa.Http.csproj" />
        <ProjectReference Include="../../../../src/modules/Elsa.Identity/Elsa.Identity.csproj" />
		<ProjectReference Include="../../../../src/modules/Elsa.Expressions.JavaScript/Elsa.Expressions.JavaScript.csproj" />
        <ProjectReference Include="../../../../src/modules/Elsa.Workflows.Api/Elsa.Workflows.Api.csproj" />
        <PackageReference Include="JetBrains.Annotations" />
    </ItemGroup>

</Project>
