<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Include>[Elsa.Bpmn]*</Include>
        <Threshold>1</Threshold>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Bpmn.Interchange"/>
        <PackageReference Include="Bpmn.Model"/>
        <PackageReference Include="Bpmn.Semantics"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\common\Elsa.Testing.Shared\Elsa.Testing.Shared.csproj"/>
        <ProjectReference Include="..\..\..\src\modules\Elsa.Bpmn\Elsa.Bpmn.csproj"/>
        <ProjectReference Include="..\..\..\src\modules\Elsa.Bpmn.Interchange\Elsa.Bpmn.Interchange.csproj"/>
    </ItemGroup>

</Project>
