<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <UseTUnit>true</UseTUnit>
        <Include>[Elsa.Http]*</Include>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="TUnit.AspNetCore" />
      <ProjectReference Include="..\..\..\src\modules\Elsa.Http\Elsa.Http.csproj" />
    </ItemGroup>

</Project>
