<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <Description>Provides a UI for managing agents.</Description>
        <PackageTags>elsa extension studio module agent ai llm semantic kernel</PackageTags>
    </PropertyGroup>

    <ItemGroup Label="Elsa" Condition="$(UseProjectReferences) == true">
        <ProjectReference Include="..\..\..\..\..\elsa-studio\src\modules\Elsa.Studio.Workflows\Elsa.Studio.Workflows.csproj"/>
    </ItemGroup>

    <ItemGroup Label="Elsa" Condition="$(UseProjectReferences) != true">
        <PackageReference Include="Elsa.Studio.Workflows"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Blazored.FluentValidation"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Elsa.Agents.Models\Elsa.Agents.Models.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
      <Content Update="Assets\document-review-process.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\hello-world-console.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\hello-world-http.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\content-pipeline.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\content-writer.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\customer-support.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\loan-application-1.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\text-document-oracle.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
      <Content Update="Assets\loan-application-2.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
