// <auto-generated />
using System;
using Elsa.ExternalAuthentication.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elsa.ExternalAuthentication.Persistence.EFCore.PostgreSql.Migrations.ExternalAuthentication
{
    [DbContext(typeof(ExternalAuthenticationElsaDbContext))]
    [Migration("20260731030322_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Elsa")
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.ExternalAuthenticationRegistryVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ExternalAuthenticationRegistryVersions", "Elsa");
                });

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.PersistedAuthorizationGrant", b =>
                {
                    b.Property<string>("CodeHash")
                        .HasColumnType("text");

                    b.Property<string>("CallbackUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalSessionId")
                        .HasColumnType("text");

                    b.Property<string>("PkceChallenge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodeHash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_ExternalAuthenticationAuthorizationGrant_ExpiresAt");

                    b.ToTable("ExternalAuthenticationAuthorizationGrants", "Elsa");
                });

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.PersistedBrokerTransaction", b =>
                {
                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("HandleHash")
                        .HasColumnType("text");

                    b.Property<string>("CallbackUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientState")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionKey")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionMaterialRevision")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("PkceChallenge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ProviderNonce")
                        .HasColumnType("text");

                    b.Property<string>("ReturnPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretGenerationFingerprint")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Purpose", "HandleHash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_ExternalAuthenticationBrokerTransaction_ExpiresAt");

                    b.ToTable("ExternalAuthenticationBrokerTransactions", "Elsa");
                });

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.PersistedConnectionObservation", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DurationTicks")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestedMaterialRevision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ConnectionId");

                    b.ToTable("ExternalAuthenticationConnectionObservations", "Elsa");
                });

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.PersistedExternalAuthenticationSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthenticationClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionMaterialRevision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentRefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalGrantsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ProtectedUpstreamLogoutHint")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("RefreshExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RefreshGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecretGenerationFingerprint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionKey")
                        .HasDatabaseName("IX_ExternalAuthenticationSession_ConnectionKey");

                    b.HasIndex("CurrentRefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalAuthenticationSession_RefreshTokenHash");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_ExternalAuthenticationSession_TenantId_UserId");

                    b.ToTable("ExternalAuthenticationSessions", "Elsa");
                });

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.PersistedExternalIdentityLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSignedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectHint")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "UserId")
                        .HasDatabaseName("IX_ExternalIdentityLink_TenantId_UserId");

                    b.HasIndex("TenantId", "ConnectionKey", "Issuer", "SubjectHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalIdentityLink_Identity");

                    b.ToTable("ExternalIdentityLinks", "Elsa");
                });

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.PersistedIdentityProviderConnection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AdapterSettingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AdapterSettingsVersion")
                        .HasColumnType("integer");

                    b.Property<string>("AdapterType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimProjectionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconId")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialRevision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OverridesConfigurationConnection")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionGrantSourcesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("SecretBindingsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnlinkedPolicyJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpstreamLogoutMode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialRevision")
                        .HasDatabaseName("IX_IdentityProviderConnection_MaterialRevision");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("IX_IdentityProviderConnection_TenantId_Key");

                    b.ToTable("IdentityProviderConnections", "Elsa");
                });

            modelBuilder.Entity("Elsa.ExternalAuthentication.Persistence.EFCore.PersistedPreviewResult", b =>
                {
                    b.Property<string>("HandleHash")
                        .HasColumnType("text");

                    b.Property<string>("AdministratorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpiresAtUtcTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaskedSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialRevision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PermissionProjectionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PolicyDecision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectedClaimsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HandleHash");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_ExternalAuthenticationPreviewResult_ExpiresAt");

                    b.ToTable("ExternalAuthenticationPreviewResults", "Elsa");
                });
#pragma warning restore 612, 618
        }
    }
}
