version: '3.7'

services:
    
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - /var/lib/mongodb:/var/lib/mongodb
            
    azureblobstorage:
        image: mcr.microsoft.com/azure-blob-storage
        
    redis:
        image: redis
        ports:
            - "6379:6379"
                
    rabbitmq:
        image: "rabbitmq:3-management"
        ports:
            - "15672:15672"
            - "5672:5672"

    smtp4dev:
        image: rnwood/smtp4dev:linux-amd64-3.1.0-ci0856
        ports:
            - "3000:80"
            - "2525:25"