/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';
import {
  WorkflowFormatDescriptorDictionary,
} from '@elsa-workflows/elsa-workflow-designer/dist/types/models';

export namespace Components {
  interface AppGithubLink {}
  interface AppHome {}
  interface AppRoot {}
  interface AppSidebar {}
  interface AppTest {}
  interface AppWorkflowDefinitions {}
  interface AppWorkflowEditor {
    'match': MatchResults;
    'workflowFormats': WorkflowFormatDescriptorDictionary;
  }
}

declare global {


  interface HTMLAppGithubLinkElement extends Components.AppGithubLink, HTMLStencilElement {}
  var HTMLAppGithubLinkElement: {
    prototype: HTMLAppGithubLinkElement;
    new (): HTMLAppGithubLinkElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSidebarElement extends Components.AppSidebar, HTMLStencilElement {}
  var HTMLAppSidebarElement: {
    prototype: HTMLAppSidebarElement;
    new (): HTMLAppSidebarElement;
  };

  interface HTMLAppTestElement extends Components.AppTest, HTMLStencilElement {}
  var HTMLAppTestElement: {
    prototype: HTMLAppTestElement;
    new (): HTMLAppTestElement;
  };

  interface HTMLAppWorkflowDefinitionsElement extends Components.AppWorkflowDefinitions, HTMLStencilElement {}
  var HTMLAppWorkflowDefinitionsElement: {
    prototype: HTMLAppWorkflowDefinitionsElement;
    new (): HTMLAppWorkflowDefinitionsElement;
  };

  interface HTMLAppWorkflowEditorElement extends Components.AppWorkflowEditor, HTMLStencilElement {}
  var HTMLAppWorkflowEditorElement: {
    prototype: HTMLAppWorkflowEditorElement;
    new (): HTMLAppWorkflowEditorElement;
  };
  interface HTMLElementTagNameMap {
    'app-github-link': HTMLAppGithubLinkElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'app-sidebar': HTMLAppSidebarElement;
    'app-test': HTMLAppTestElement;
    'app-workflow-definitions': HTMLAppWorkflowDefinitionsElement;
    'app-workflow-editor': HTMLAppWorkflowEditorElement;
  }
}

declare namespace LocalJSX {
  interface AppGithubLink extends JSXBase.HTMLAttributes<HTMLAppGithubLinkElement> {}
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppRoot extends JSXBase.HTMLAttributes<HTMLAppRootElement> {}
  interface AppSidebar extends JSXBase.HTMLAttributes<HTMLAppSidebarElement> {}
  interface AppTest extends JSXBase.HTMLAttributes<HTMLAppTestElement> {}
  interface AppWorkflowDefinitions extends JSXBase.HTMLAttributes<HTMLAppWorkflowDefinitionsElement> {}
  interface AppWorkflowEditor extends JSXBase.HTMLAttributes<HTMLAppWorkflowEditorElement> {
    'match'?: MatchResults;
    'workflowFormats'?: WorkflowFormatDescriptorDictionary;
  }

  interface IntrinsicElements {
    'app-github-link': AppGithubLink;
    'app-home': AppHome;
    'app-root': AppRoot;
    'app-sidebar': AppSidebar;
    'app-test': AppTest;
    'app-workflow-definitions': AppWorkflowDefinitions;
    'app-workflow-editor': AppWorkflowEditor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


