<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="../../../../../src/common/Elsa.Testing.Shared/Elsa.Testing.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../../../../src/extensions/mqtt/Elsa.Mqtt/Elsa.Mqtt.csproj" />
	</ItemGroup>

</Project>
