<Project>

    <Import Project="../../Directory.Build.props"/>

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <CollectCoverage>false</CollectCoverage>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BenchmarkDotNet"/>
    </ItemGroup>

</Project>
