apiVersion: apps/v1
kind: Deployment
metadata:
  name: elsa-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elsa-server
  template:
    metadata:
      labels:
        app: elsa-server
    spec:
      serviceAccountName: proto-cluster
      containers:
        - name: elsa-server
          imagePullPolicy: Never
          image: elsa-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: "Runtime__ProtoActor__ClusterProvider"
              value: "Kubernetes"
            - name: "ProtoActor__AdvertisedHost"  # This is the host we expose to other cluster members.
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
