import { Secret } from "../secret.model";

export const SqlServer: Secret = {
  category: "Sql",
  customAttributes: {},
  description: "Sql connection data",
  displayName: "MSSQL Server secret",
  inputProperties: [
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Data Source",
      name: "Data Source",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Initial Catalog",
      name: "Initial Catalog",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.Int64",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Integrated Security",
      name: "Integrated Security",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Encrypt",
      name: "Encrypt",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "MultipleActiveResultSets",
      name: "MultipleActiveResultSets",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Password",
      name: "Password",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "User ID",
      name: "User ID",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.Int64",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Connection Timeout",
      name: "Connection Timeout",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
  ],
  properties: [
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Data Source",
      name: "Data Source",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Initial Catalog",
      name: "Initial Catalog",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.Int64",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Integrated Security",
      name: "Integrated Security",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Encrypt",
      name: "Encrypt",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "MultipleActiveResultSets",
      name: "MultipleActiveResultSets",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Password",
      name: "Password",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "User ID",
      name: "User ID",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.Int64",
      uiHint: "single-line",
    },
    {
      considerValuesAsOutcomes: false,
      disableWorkflowProviderSelection: false,
      isBrowsable: true,
      isDesignerCritical: false,
      isReadOnly: false,
      label: "Connection Timeout",
      name: "Connection Timeout",
      order: 0,
      supportedSyntaxes: ["JavaScript", "Liquid"],
      type: "System.String",
      uiHint: "single-line",
    },
  ],
  type: "MSSQLServer"
}