/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActionDefinition, ActionInvokedArgs, Activity, ActivityDescriptor, ActivitySelectedArgs, ContainerSelectedArgs, GraphUpdatedArgs, TabChangedArgs, TabDefinition, Trigger, TriggerDescriptor, Workflow, WorkflowInstance, WorkflowInstanceSummary, WorkflowSummary } from "./models";
import { ActivityUpdatedArgs, DeleteActivityRequestedArgs } from "./components/designer/activity-properties-editor/activity-properties-editor";
import { AddActivityArgs } from "./components/designer/canvas/canvas";
import { NodeInputContext } from "./services/node-input-driver";
import { MenuItem } from "./components/shared/context-menu/models";
import { DropdownButtonItem, DropdownButtonOrigin } from "./components/shared/dropdown-button/models";
import { AddActivityArgs as AddActivityArgs1 } from "./components/designer/canvas/canvas";
import { PagerData } from "./components/shared/pager/pager";
import { PanelPosition, PanelStateChangedArgs } from "./components/designer/panel/models";
import { Graph } from "@antv/x6";
import { TriggerDeselectedArgs, TriggerSelectedArgs, TriggersUpdatedArgs } from "./components/designer/trigger-container/trigger-container";
import { DeleteTriggerRequestedArgs, TriggerUpdatedArgs } from "./components/designer/trigger-properties-editor/trigger-properties-editor";
import { WorkflowUpdatedArgs } from "./components/designer/workflow-editor/workflow-editor";
import { ActivityDriverRegistry } from "./services";
import { WorkflowPropsUpdatedArgs } from "./components/designer/workflow-properties-editor/workflow-properties-editor";
import { PublishClickedArgs } from "./components/toolbar/workflow-publish-button/workflow-publish-button";
export namespace Components {
    interface ElsaActivityPropertiesEditor {
        "activity"?: Activity;
        "activityDescriptors": Array<ActivityDescriptor>;
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
    }
    interface ElsaCanvas {
        "addActivity": (args: AddActivityArgs) => Promise<void>;
        "exportGraph": () => Promise<Activity>;
        "importGraph": (root: Activity) => Promise<void>;
        "interactiveMode": boolean;
        "updateLayout": () => Promise<void>;
    }
    interface ElsaCheckListInput {
        "inputContext": NodeInputContext;
    }
    interface ElsaContextMenu {
        "menuItems": Array<MenuItem>;
    }
    interface ElsaDropdownButton {
        "icon"?: any;
        "items": Array<DropdownButtonItem>;
        "origin": DropdownButtonOrigin;
        "text": string;
    }
    interface ElsaDropdownInput {
        "inputContext": NodeInputContext;
    }
    interface ElsaFlowchart {
        "activityDescriptors": Array<ActivityDescriptor>;
        "addActivity": (args: AddActivityArgs) => Promise<void>;
        "exportRoot": () => Promise<Activity>;
        "importRoot": (root: Activity) => Promise<void>;
        "interactiveMode": boolean;
        "root"?: Activity;
        "updateLayout": () => Promise<void>;
    }
    interface ElsaFormPanel {
        "actions": Array<ActionDefinition>;
        "headerText": string;
        "selectedTabIndex"?: number;
        "tabs": Array<TabDefinition>;
    }
    interface ElsaModalDialog {
        "actions": Array<ActionDefinition>;
        "hide": (animate?: boolean) => Promise<void>;
        "show": (animate?: boolean) => Promise<void>;
        "size": string;
    }
    interface ElsaPager {
        "page": number;
        "pageSize": number;
        "totalCount": number;
    }
    interface ElsaPanel {
        "position": PanelPosition;
    }
    interface ElsaSingleLineInput {
        "inputContext": NodeInputContext;
    }
    interface ElsaSlideOverPanel {
        "actions": Array<ActionDefinition>;
        "expand": boolean;
        "headerText": string;
        "hide": () => Promise<void>;
        "selectedTab"?: TabDefinition;
        "show": () => Promise<void>;
        "tabs": Array<TabDefinition>;
    }
    interface ElsaStudio {
        "serverUrl": string;
    }
    interface ElsaToolbox {
        "graph": Graph;
    }
    interface ElsaToolboxActivities {
        "activityDescriptors": Array<ActivityDescriptor>;
        "graph": Graph;
        "triggerDescriptors": Array<TriggerDescriptor>;
    }
    interface ElsaToolboxTriggers {
        "activityDescriptors": Array<ActivityDescriptor>;
        "graph": Graph;
        "triggerDescriptors": Array<TriggerDescriptor>;
    }
    interface ElsaTriggerContainer {
        "deselectAll": () => Promise<void>;
        "interactiveMode": boolean;
        "triggerDescriptors": Array<TriggerDescriptor>;
        "triggers": Array<Trigger>;
    }
    interface ElsaTriggerPropertiesEditor {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
        "trigger"?: Trigger;
        "triggerDescriptors": Array<TriggerDescriptor>;
    }
    interface ElsaWorkflowBrowser {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
    }
    interface ElsaWorkflowEditor {
        "activityDescriptors": Array<ActivityDescriptor>;
        "getWorkflow": () => Promise<Workflow>;
        "importWorkflow": (workflow: Workflow, workflowInstance?: WorkflowInstance) => Promise<void>;
        "importWorkflowMetadata": (workflow: Workflow) => Promise<void>;
        "registerActivityDrivers": (register: (registry: ActivityDriverRegistry) => void) => Promise<void>;
        "triggerDescriptors": Array<TriggerDescriptor>;
    }
    interface ElsaWorkflowInstanceBrowser {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
    }
    interface ElsaWorkflowPropertiesEditor {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
        "workflow"?: Workflow;
    }
    interface ElsaWorkflowPublishButton {
        "publishing": boolean;
    }
    interface ElsaWorkflowToolbar {
    }
    interface ElsaWorkflowToolbarMenu {
    }
}
declare global {
    interface HTMLElsaActivityPropertiesEditorElement extends Components.ElsaActivityPropertiesEditor, HTMLStencilElement {
    }
    var HTMLElsaActivityPropertiesEditorElement: {
        prototype: HTMLElsaActivityPropertiesEditorElement;
        new (): HTMLElsaActivityPropertiesEditorElement;
    };
    interface HTMLElsaCanvasElement extends Components.ElsaCanvas, HTMLStencilElement {
    }
    var HTMLElsaCanvasElement: {
        prototype: HTMLElsaCanvasElement;
        new (): HTMLElsaCanvasElement;
    };
    interface HTMLElsaCheckListInputElement extends Components.ElsaCheckListInput, HTMLStencilElement {
    }
    var HTMLElsaCheckListInputElement: {
        prototype: HTMLElsaCheckListInputElement;
        new (): HTMLElsaCheckListInputElement;
    };
    interface HTMLElsaContextMenuElement extends Components.ElsaContextMenu, HTMLStencilElement {
    }
    var HTMLElsaContextMenuElement: {
        prototype: HTMLElsaContextMenuElement;
        new (): HTMLElsaContextMenuElement;
    };
    interface HTMLElsaDropdownButtonElement extends Components.ElsaDropdownButton, HTMLStencilElement {
    }
    var HTMLElsaDropdownButtonElement: {
        prototype: HTMLElsaDropdownButtonElement;
        new (): HTMLElsaDropdownButtonElement;
    };
    interface HTMLElsaDropdownInputElement extends Components.ElsaDropdownInput, HTMLStencilElement {
    }
    var HTMLElsaDropdownInputElement: {
        prototype: HTMLElsaDropdownInputElement;
        new (): HTMLElsaDropdownInputElement;
    };
    interface HTMLElsaFlowchartElement extends Components.ElsaFlowchart, HTMLStencilElement {
    }
    var HTMLElsaFlowchartElement: {
        prototype: HTMLElsaFlowchartElement;
        new (): HTMLElsaFlowchartElement;
    };
    interface HTMLElsaFormPanelElement extends Components.ElsaFormPanel, HTMLStencilElement {
    }
    var HTMLElsaFormPanelElement: {
        prototype: HTMLElsaFormPanelElement;
        new (): HTMLElsaFormPanelElement;
    };
    interface HTMLElsaModalDialogElement extends Components.ElsaModalDialog, HTMLStencilElement {
    }
    var HTMLElsaModalDialogElement: {
        prototype: HTMLElsaModalDialogElement;
        new (): HTMLElsaModalDialogElement;
    };
    interface HTMLElsaPagerElement extends Components.ElsaPager, HTMLStencilElement {
    }
    var HTMLElsaPagerElement: {
        prototype: HTMLElsaPagerElement;
        new (): HTMLElsaPagerElement;
    };
    interface HTMLElsaPanelElement extends Components.ElsaPanel, HTMLStencilElement {
    }
    var HTMLElsaPanelElement: {
        prototype: HTMLElsaPanelElement;
        new (): HTMLElsaPanelElement;
    };
    interface HTMLElsaSingleLineInputElement extends Components.ElsaSingleLineInput, HTMLStencilElement {
    }
    var HTMLElsaSingleLineInputElement: {
        prototype: HTMLElsaSingleLineInputElement;
        new (): HTMLElsaSingleLineInputElement;
    };
    interface HTMLElsaSlideOverPanelElement extends Components.ElsaSlideOverPanel, HTMLStencilElement {
    }
    var HTMLElsaSlideOverPanelElement: {
        prototype: HTMLElsaSlideOverPanelElement;
        new (): HTMLElsaSlideOverPanelElement;
    };
    interface HTMLElsaStudioElement extends Components.ElsaStudio, HTMLStencilElement {
    }
    var HTMLElsaStudioElement: {
        prototype: HTMLElsaStudioElement;
        new (): HTMLElsaStudioElement;
    };
    interface HTMLElsaToolboxElement extends Components.ElsaToolbox, HTMLStencilElement {
    }
    var HTMLElsaToolboxElement: {
        prototype: HTMLElsaToolboxElement;
        new (): HTMLElsaToolboxElement;
    };
    interface HTMLElsaToolboxActivitiesElement extends Components.ElsaToolboxActivities, HTMLStencilElement {
    }
    var HTMLElsaToolboxActivitiesElement: {
        prototype: HTMLElsaToolboxActivitiesElement;
        new (): HTMLElsaToolboxActivitiesElement;
    };
    interface HTMLElsaToolboxTriggersElement extends Components.ElsaToolboxTriggers, HTMLStencilElement {
    }
    var HTMLElsaToolboxTriggersElement: {
        prototype: HTMLElsaToolboxTriggersElement;
        new (): HTMLElsaToolboxTriggersElement;
    };
    interface HTMLElsaTriggerContainerElement extends Components.ElsaTriggerContainer, HTMLStencilElement {
    }
    var HTMLElsaTriggerContainerElement: {
        prototype: HTMLElsaTriggerContainerElement;
        new (): HTMLElsaTriggerContainerElement;
    };
    interface HTMLElsaTriggerPropertiesEditorElement extends Components.ElsaTriggerPropertiesEditor, HTMLStencilElement {
    }
    var HTMLElsaTriggerPropertiesEditorElement: {
        prototype: HTMLElsaTriggerPropertiesEditorElement;
        new (): HTMLElsaTriggerPropertiesEditorElement;
    };
    interface HTMLElsaWorkflowBrowserElement extends Components.ElsaWorkflowBrowser, HTMLStencilElement {
    }
    var HTMLElsaWorkflowBrowserElement: {
        prototype: HTMLElsaWorkflowBrowserElement;
        new (): HTMLElsaWorkflowBrowserElement;
    };
    interface HTMLElsaWorkflowEditorElement extends Components.ElsaWorkflowEditor, HTMLStencilElement {
    }
    var HTMLElsaWorkflowEditorElement: {
        prototype: HTMLElsaWorkflowEditorElement;
        new (): HTMLElsaWorkflowEditorElement;
    };
    interface HTMLElsaWorkflowInstanceBrowserElement extends Components.ElsaWorkflowInstanceBrowser, HTMLStencilElement {
    }
    var HTMLElsaWorkflowInstanceBrowserElement: {
        prototype: HTMLElsaWorkflowInstanceBrowserElement;
        new (): HTMLElsaWorkflowInstanceBrowserElement;
    };
    interface HTMLElsaWorkflowPropertiesEditorElement extends Components.ElsaWorkflowPropertiesEditor, HTMLStencilElement {
    }
    var HTMLElsaWorkflowPropertiesEditorElement: {
        prototype: HTMLElsaWorkflowPropertiesEditorElement;
        new (): HTMLElsaWorkflowPropertiesEditorElement;
    };
    interface HTMLElsaWorkflowPublishButtonElement extends Components.ElsaWorkflowPublishButton, HTMLStencilElement {
    }
    var HTMLElsaWorkflowPublishButtonElement: {
        prototype: HTMLElsaWorkflowPublishButtonElement;
        new (): HTMLElsaWorkflowPublishButtonElement;
    };
    interface HTMLElsaWorkflowToolbarElement extends Components.ElsaWorkflowToolbar, HTMLStencilElement {
    }
    var HTMLElsaWorkflowToolbarElement: {
        prototype: HTMLElsaWorkflowToolbarElement;
        new (): HTMLElsaWorkflowToolbarElement;
    };
    interface HTMLElsaWorkflowToolbarMenuElement extends Components.ElsaWorkflowToolbarMenu, HTMLStencilElement {
    }
    var HTMLElsaWorkflowToolbarMenuElement: {
        prototype: HTMLElsaWorkflowToolbarMenuElement;
        new (): HTMLElsaWorkflowToolbarMenuElement;
    };
    interface HTMLElementTagNameMap {
        "elsa-activity-properties-editor": HTMLElsaActivityPropertiesEditorElement;
        "elsa-canvas": HTMLElsaCanvasElement;
        "elsa-check-list-input": HTMLElsaCheckListInputElement;
        "elsa-context-menu": HTMLElsaContextMenuElement;
        "elsa-dropdown-button": HTMLElsaDropdownButtonElement;
        "elsa-dropdown-input": HTMLElsaDropdownInputElement;
        "elsa-flowchart": HTMLElsaFlowchartElement;
        "elsa-form-panel": HTMLElsaFormPanelElement;
        "elsa-modal-dialog": HTMLElsaModalDialogElement;
        "elsa-pager": HTMLElsaPagerElement;
        "elsa-panel": HTMLElsaPanelElement;
        "elsa-single-line-input": HTMLElsaSingleLineInputElement;
        "elsa-slide-over-panel": HTMLElsaSlideOverPanelElement;
        "elsa-studio": HTMLElsaStudioElement;
        "elsa-toolbox": HTMLElsaToolboxElement;
        "elsa-toolbox-activities": HTMLElsaToolboxActivitiesElement;
        "elsa-toolbox-triggers": HTMLElsaToolboxTriggersElement;
        "elsa-trigger-container": HTMLElsaTriggerContainerElement;
        "elsa-trigger-properties-editor": HTMLElsaTriggerPropertiesEditorElement;
        "elsa-workflow-browser": HTMLElsaWorkflowBrowserElement;
        "elsa-workflow-editor": HTMLElsaWorkflowEditorElement;
        "elsa-workflow-instance-browser": HTMLElsaWorkflowInstanceBrowserElement;
        "elsa-workflow-properties-editor": HTMLElsaWorkflowPropertiesEditorElement;
        "elsa-workflow-publish-button": HTMLElsaWorkflowPublishButtonElement;
        "elsa-workflow-toolbar": HTMLElsaWorkflowToolbarElement;
        "elsa-workflow-toolbar-menu": HTMLElsaWorkflowToolbarMenuElement;
    }
}
declare namespace LocalJSX {
    interface ElsaActivityPropertiesEditor {
        "activity"?: Activity;
        "activityDescriptors"?: Array<ActivityDescriptor>;
        "onActivityUpdated"?: (event: CustomEvent<ActivityUpdatedArgs>) => void;
        "onDeleteActivityRequested"?: (event: CustomEvent<DeleteActivityRequestedArgs>) => void;
    }
    interface ElsaCanvas {
        "interactiveMode"?: boolean;
    }
    interface ElsaCheckListInput {
        "inputContext"?: NodeInputContext;
    }
    interface ElsaContextMenu {
        "menuItems"?: Array<MenuItem>;
    }
    interface ElsaDropdownButton {
        "icon"?: any;
        "items"?: Array<DropdownButtonItem>;
        "onItemSelected"?: (event: CustomEvent<DropdownButtonItem>) => void;
        "origin"?: DropdownButtonOrigin;
        "text"?: string;
    }
    interface ElsaDropdownInput {
        "inputContext"?: NodeInputContext;
    }
    interface ElsaFlowchart {
        "activityDescriptors"?: Array<ActivityDescriptor>;
        "interactiveMode"?: boolean;
        "onActivitySelected"?: (event: CustomEvent<ActivitySelectedArgs>) => void;
        "onContainerSelected"?: (event: CustomEvent<ContainerSelectedArgs>) => void;
        "onGraphUpdated"?: (event: CustomEvent<GraphUpdatedArgs>) => void;
        "root"?: Activity;
    }
    interface ElsaFormPanel {
        "actions"?: Array<ActionDefinition>;
        "headerText"?: string;
        "onActionInvoked"?: (event: CustomEvent<ActionInvokedArgs>) => void;
        "onSelectedTabIndexChanged"?: (event: CustomEvent<TabChangedArgs>) => void;
        "onSubmitted"?: (event: CustomEvent<FormData>) => void;
        "selectedTabIndex"?: number;
        "tabs"?: Array<TabDefinition>;
    }
    interface ElsaModalDialog {
        "actions"?: Array<ActionDefinition>;
        "onActionInvoked"?: (event: CustomEvent<ActionInvokedArgs>) => void;
        "onHidden"?: (event: CustomEvent<any>) => void;
        "onShown"?: (event: CustomEvent<any>) => void;
        "size"?: string;
    }
    interface ElsaPager {
        "onPaginated"?: (event: CustomEvent<PagerData>) => void;
        "page"?: number;
        "pageSize"?: number;
        "totalCount"?: number;
    }
    interface ElsaPanel {
        "onExpandedStateChanged"?: (event: CustomEvent<PanelStateChangedArgs>) => void;
        "position"?: PanelPosition;
    }
    interface ElsaSingleLineInput {
        "inputContext"?: NodeInputContext;
    }
    interface ElsaSlideOverPanel {
        "actions"?: Array<ActionDefinition>;
        "expand"?: boolean;
        "headerText"?: string;
        "onCollapsed"?: (event: CustomEvent<any>) => void;
        "onSubmitted"?: (event: CustomEvent<FormData>) => void;
        "selectedTab"?: TabDefinition;
        "tabs"?: Array<TabDefinition>;
    }
    interface ElsaStudio {
        "serverUrl"?: string;
    }
    interface ElsaToolbox {
        "graph"?: Graph;
    }
    interface ElsaToolboxActivities {
        "activityDescriptors"?: Array<ActivityDescriptor>;
        "graph"?: Graph;
        "triggerDescriptors"?: Array<TriggerDescriptor>;
    }
    interface ElsaToolboxTriggers {
        "activityDescriptors"?: Array<ActivityDescriptor>;
        "graph"?: Graph;
        "triggerDescriptors"?: Array<TriggerDescriptor>;
    }
    interface ElsaTriggerContainer {
        "interactiveMode"?: boolean;
        "onTriggerDeselected"?: (event: CustomEvent<TriggerDeselectedArgs>) => void;
        "onTriggerSelected"?: (event: CustomEvent<TriggerSelectedArgs>) => void;
        "onTriggersUpdated"?: (event: CustomEvent<TriggersUpdatedArgs>) => void;
        "triggerDescriptors"?: Array<TriggerDescriptor>;
        "triggers"?: Array<Trigger>;
    }
    interface ElsaTriggerPropertiesEditor {
        "onDeleteTriggerRequested"?: (event: CustomEvent<DeleteTriggerRequestedArgs>) => void;
        "onTriggerUpdated"?: (event: CustomEvent<TriggerUpdatedArgs>) => void;
        "trigger"?: Trigger;
        "triggerDescriptors"?: Array<TriggerDescriptor>;
    }
    interface ElsaWorkflowBrowser {
        "onWorkflowDefinitionSelected"?: (event: CustomEvent<WorkflowSummary>) => void;
    }
    interface ElsaWorkflowEditor {
        "activityDescriptors"?: Array<ActivityDescriptor>;
        "onWorkflowUpdated"?: (event: CustomEvent<WorkflowUpdatedArgs>) => void;
        "triggerDescriptors"?: Array<TriggerDescriptor>;
    }
    interface ElsaWorkflowInstanceBrowser {
        "onWorkflowInstanceSelected"?: (event: CustomEvent<WorkflowInstanceSummary>) => void;
    }
    interface ElsaWorkflowPropertiesEditor {
        "onWorkflowPropsUpdated"?: (event: CustomEvent<WorkflowPropsUpdatedArgs>) => void;
        "workflow"?: Workflow;
    }
    interface ElsaWorkflowPublishButton {
        "onExportClicked"?: (event: CustomEvent<any>) => void;
        "onImportClicked"?: (event: CustomEvent<File>) => void;
        "onNewClicked"?: (event: CustomEvent<any>) => void;
        "onPublishClicked"?: (event: CustomEvent<PublishClickedArgs>) => void;
        "onUnPublishClicked"?: (event: CustomEvent<any>) => void;
        "publishing"?: boolean;
    }
    interface ElsaWorkflowToolbar {
    }
    interface ElsaWorkflowToolbarMenu {
    }
    interface IntrinsicElements {
        "elsa-activity-properties-editor": ElsaActivityPropertiesEditor;
        "elsa-canvas": ElsaCanvas;
        "elsa-check-list-input": ElsaCheckListInput;
        "elsa-context-menu": ElsaContextMenu;
        "elsa-dropdown-button": ElsaDropdownButton;
        "elsa-dropdown-input": ElsaDropdownInput;
        "elsa-flowchart": ElsaFlowchart;
        "elsa-form-panel": ElsaFormPanel;
        "elsa-modal-dialog": ElsaModalDialog;
        "elsa-pager": ElsaPager;
        "elsa-panel": ElsaPanel;
        "elsa-single-line-input": ElsaSingleLineInput;
        "elsa-slide-over-panel": ElsaSlideOverPanel;
        "elsa-studio": ElsaStudio;
        "elsa-toolbox": ElsaToolbox;
        "elsa-toolbox-activities": ElsaToolboxActivities;
        "elsa-toolbox-triggers": ElsaToolboxTriggers;
        "elsa-trigger-container": ElsaTriggerContainer;
        "elsa-trigger-properties-editor": ElsaTriggerPropertiesEditor;
        "elsa-workflow-browser": ElsaWorkflowBrowser;
        "elsa-workflow-editor": ElsaWorkflowEditor;
        "elsa-workflow-instance-browser": ElsaWorkflowInstanceBrowser;
        "elsa-workflow-properties-editor": ElsaWorkflowPropertiesEditor;
        "elsa-workflow-publish-button": ElsaWorkflowPublishButton;
        "elsa-workflow-toolbar": ElsaWorkflowToolbar;
        "elsa-workflow-toolbar-menu": ElsaWorkflowToolbarMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elsa-activity-properties-editor": LocalJSX.ElsaActivityPropertiesEditor & JSXBase.HTMLAttributes<HTMLElsaActivityPropertiesEditorElement>;
            "elsa-canvas": LocalJSX.ElsaCanvas & JSXBase.HTMLAttributes<HTMLElsaCanvasElement>;
            "elsa-check-list-input": LocalJSX.ElsaCheckListInput & JSXBase.HTMLAttributes<HTMLElsaCheckListInputElement>;
            "elsa-context-menu": LocalJSX.ElsaContextMenu & JSXBase.HTMLAttributes<HTMLElsaContextMenuElement>;
            "elsa-dropdown-button": LocalJSX.ElsaDropdownButton & JSXBase.HTMLAttributes<HTMLElsaDropdownButtonElement>;
            "elsa-dropdown-input": LocalJSX.ElsaDropdownInput & JSXBase.HTMLAttributes<HTMLElsaDropdownInputElement>;
            "elsa-flowchart": LocalJSX.ElsaFlowchart & JSXBase.HTMLAttributes<HTMLElsaFlowchartElement>;
            "elsa-form-panel": LocalJSX.ElsaFormPanel & JSXBase.HTMLAttributes<HTMLElsaFormPanelElement>;
            "elsa-modal-dialog": LocalJSX.ElsaModalDialog & JSXBase.HTMLAttributes<HTMLElsaModalDialogElement>;
            "elsa-pager": LocalJSX.ElsaPager & JSXBase.HTMLAttributes<HTMLElsaPagerElement>;
            "elsa-panel": LocalJSX.ElsaPanel & JSXBase.HTMLAttributes<HTMLElsaPanelElement>;
            "elsa-single-line-input": LocalJSX.ElsaSingleLineInput & JSXBase.HTMLAttributes<HTMLElsaSingleLineInputElement>;
            "elsa-slide-over-panel": LocalJSX.ElsaSlideOverPanel & JSXBase.HTMLAttributes<HTMLElsaSlideOverPanelElement>;
            "elsa-studio": LocalJSX.ElsaStudio & JSXBase.HTMLAttributes<HTMLElsaStudioElement>;
            "elsa-toolbox": LocalJSX.ElsaToolbox & JSXBase.HTMLAttributes<HTMLElsaToolboxElement>;
            "elsa-toolbox-activities": LocalJSX.ElsaToolboxActivities & JSXBase.HTMLAttributes<HTMLElsaToolboxActivitiesElement>;
            "elsa-toolbox-triggers": LocalJSX.ElsaToolboxTriggers & JSXBase.HTMLAttributes<HTMLElsaToolboxTriggersElement>;
            "elsa-trigger-container": LocalJSX.ElsaTriggerContainer & JSXBase.HTMLAttributes<HTMLElsaTriggerContainerElement>;
            "elsa-trigger-properties-editor": LocalJSX.ElsaTriggerPropertiesEditor & JSXBase.HTMLAttributes<HTMLElsaTriggerPropertiesEditorElement>;
            "elsa-workflow-browser": LocalJSX.ElsaWorkflowBrowser & JSXBase.HTMLAttributes<HTMLElsaWorkflowBrowserElement>;
            "elsa-workflow-editor": LocalJSX.ElsaWorkflowEditor & JSXBase.HTMLAttributes<HTMLElsaWorkflowEditorElement>;
            "elsa-workflow-instance-browser": LocalJSX.ElsaWorkflowInstanceBrowser & JSXBase.HTMLAttributes<HTMLElsaWorkflowInstanceBrowserElement>;
            "elsa-workflow-properties-editor": LocalJSX.ElsaWorkflowPropertiesEditor & JSXBase.HTMLAttributes<HTMLElsaWorkflowPropertiesEditorElement>;
            "elsa-workflow-publish-button": LocalJSX.ElsaWorkflowPublishButton & JSXBase.HTMLAttributes<HTMLElsaWorkflowPublishButtonElement>;
            "elsa-workflow-toolbar": LocalJSX.ElsaWorkflowToolbar & JSXBase.HTMLAttributes<HTMLElsaWorkflowToolbarElement>;
            "elsa-workflow-toolbar-menu": LocalJSX.ElsaWorkflowToolbarMenu & JSXBase.HTMLAttributes<HTMLElsaWorkflowToolbarMenuElement>;
        }
    }
}
