apiVersion: v1
kind: Service
metadata:
  name: elsa-server-service
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 8001
      targetPort: 8080
  selector:
    app: elsa-server
