<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Include>[Elsa.Secrets]*,[Elsa.Studio.Secrets]*</Include>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Refit" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\common\Elsa.Testing.Shared.Integration\Elsa.Testing.Shared.Integration.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Secrets\Elsa.Secrets.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Secrets.JavaScript\Elsa.Secrets.JavaScript.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Secrets.Persistence.EFCore.Sqlite\Elsa.Secrets.Persistence.EFCore.Sqlite.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Tenants.AspNetCore\Elsa.Tenants.AspNetCore.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa\Elsa.csproj" />
    </ItemGroup>

</Project>
