// <auto-generated />
using Elsa.AI.Persistence.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.AI.Persistence.EFCore.Sqlite.Migrations.AI
{
    [DbContext(typeof(AIDbContext))]
    [Migration("20260608124921_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Elsa")
                .HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Elsa.AI.Persistence.EFCore.Entities.AIAuditRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolInvocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("ToolInvocationId");

                    b.HasIndex("TenantId", "ConversationId");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("AIAuditRecords", "Elsa");
                });

            modelBuilder.Entity("Elsa.AI.Persistence.EFCore.Entities.AIConversationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RetentionExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("AIConversations", "Elsa");
                });

            modelBuilder.Entity("Elsa.AI.Persistence.EFCore.Entities.AIProposalRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaselineWorkflowDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphDiff")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationDiagnostics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId", "ConversationId");

                    b.ToTable("AIProposals", "Elsa");
                });
#pragma warning restore 612, 618
        }
    }
}
