<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Include>[Elsa.UserTasks.Persistence.EFCore]*</Include>
        <Threshold>0</Threshold>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\modules\Elsa.UserTasks.Persistence.EFCore.Sqlite\Elsa.UserTasks.Persistence.EFCore.Sqlite.csproj" />
    </ItemGroup>
</Project>
