<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Elsa Studio bundle of commonly used packages.</Description>
        <PackageTags>elsa studio framework bundle</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\framework\Elsa.Studio.Shell\Elsa.Studio.Shell.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Authentication.Themes\Elsa.Studio.Authentication.Themes.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Authentication.UI\Elsa.Studio.Authentication.UI.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.AI\Elsa.Studio.AI.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Dashboard\Elsa.Studio.Dashboard.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Diagnostics.ConsoleLogs.Dashboard\Elsa.Studio.Diagnostics.ConsoleLogs.Dashboard.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Diagnostics.ConsoleLogs\Elsa.Studio.Diagnostics.ConsoleLogs.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Diagnostics.OpenTelemetry\Elsa.Studio.Diagnostics.OpenTelemetry.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Diagnostics.OpenTelemetry.Dashboard\Elsa.Studio.Diagnostics.OpenTelemetry.Dashboard.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Diagnostics.StructuredLogs.Dashboard\Elsa.Studio.Diagnostics.StructuredLogs.Dashboard.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Diagnostics.StructuredLogs\Elsa.Studio.Diagnostics.StructuredLogs.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Secrets\Elsa.Studio.Secrets.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.UserTasks\Elsa.Studio.UserTasks.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Settings\Elsa.Studio.Settings.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Security\Elsa.Studio.Security.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Workflows.Dashboard\Elsa.Studio.Workflows.Dashboard.csproj"/>
        <ProjectReference Include="..\..\modules\Elsa.Studio.Workflows\Elsa.Studio.Workflows.csproj"/>
    </ItemGroup>

</Project>
