// <auto-generated />
using Elsa.WorkflowSettings.Persistence.EntityFramework.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Elsa.WorkflowSettings.Persistence.EntityFramework.SqlServer.Migrations
{
    [DbContext(typeof(WorkflowSettingsContext))]
    [Migration("20250221175423_Update215")]
    partial class Update215
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Elsa")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Elsa.WorkflowSettings.Models.WorkflowSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WorkflowBlueprintId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .HasDatabaseName("IX_WorkflowSetting_Key");

                    b.HasIndex("Value")
                        .HasDatabaseName("IX_WorkflowSetting_Value");

                    b.HasIndex("WorkflowBlueprintId")
                        .HasDatabaseName("IX_WorkflowSetting_WorkflowBlueprintId");

                    b.ToTable("WorkflowSettings", "Elsa");
                });
#pragma warning restore 612, 618
        }
    }
}
