/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ActivityModel, WorkflowModel } from "./models";
export namespace Components {
    interface ElsaDesignerOrgtree {
        "workflowModel": WorkflowModel;
    }
    interface ElsaDesignerOrgtreeActivity {
        "activityModel": ActivityModel;
        "icon": string;
    }
}
declare global {
    interface HTMLElsaDesignerOrgtreeElement extends Components.ElsaDesignerOrgtree, HTMLStencilElement {
    }
    var HTMLElsaDesignerOrgtreeElement: {
        prototype: HTMLElsaDesignerOrgtreeElement;
        new (): HTMLElsaDesignerOrgtreeElement;
    };
    interface HTMLElsaDesignerOrgtreeActivityElement extends Components.ElsaDesignerOrgtreeActivity, HTMLStencilElement {
    }
    var HTMLElsaDesignerOrgtreeActivityElement: {
        prototype: HTMLElsaDesignerOrgtreeActivityElement;
        new (): HTMLElsaDesignerOrgtreeActivityElement;
    };
    interface HTMLElementTagNameMap {
        "elsa-designer-orgtree": HTMLElsaDesignerOrgtreeElement;
        "elsa-designer-orgtree-activity": HTMLElsaDesignerOrgtreeActivityElement;
    }
}
declare namespace LocalJSX {
    interface ElsaDesignerOrgtree {
        "workflowModel"?: WorkflowModel;
    }
    interface ElsaDesignerOrgtreeActivity {
        "activityModel"?: ActivityModel;
        "icon"?: string;
    }
    interface IntrinsicElements {
        "elsa-designer-orgtree": ElsaDesignerOrgtree;
        "elsa-designer-orgtree-activity": ElsaDesignerOrgtreeActivity;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elsa-designer-orgtree": LocalJSX.ElsaDesignerOrgtree & JSXBase.HTMLAttributes<HTMLElsaDesignerOrgtreeElement>;
            "elsa-designer-orgtree-activity": LocalJSX.ElsaDesignerOrgtreeActivity & JSXBase.HTMLAttributes<HTMLElsaDesignerOrgtreeActivityElement>;
        }
    }
}
