<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.Sqlite" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\modules\persistence\Elsa.Persistence.Dapper\Elsa.Persistence.Dapper.csproj" />
    </ItemGroup>

</Project>
