/* eslint-disable */
/* tslint:disable */
/* auto-generated react proxies */
import { createReactComponent } from './react-component-lib';

import type { JSX } from '@elsa-workflows/elsa-workflows-designer';



export const ElsaActivityInputEditorDialogContent = /*@__PURE__*/createReactComponent<JSX.ElsaActivityInputEditorDialogContent, HTMLElsaActivityInputEditorDialogContentElement>('elsa-activity-input-editor-dialog-content');
export const ElsaActivityOutputEditorDialogContent = /*@__PURE__*/createReactComponent<JSX.ElsaActivityOutputEditorDialogContent, HTMLElsaActivityOutputEditorDialogContentElement>('elsa-activity-output-editor-dialog-content');
export const ElsaActivityProperties = /*@__PURE__*/createReactComponent<JSX.ElsaActivityProperties, HTMLElsaActivityPropertiesElement>('elsa-activity-properties');
export const ElsaActivityPropertiesEditor = /*@__PURE__*/createReactComponent<JSX.ElsaActivityPropertiesEditor, HTMLElsaActivityPropertiesEditorElement>('elsa-activity-properties-editor');
export const ElsaBlank = /*@__PURE__*/createReactComponent<JSX.ElsaBlank, HTMLElsaBlankElement>('elsa-blank');
export const ElsaButtonGroup = /*@__PURE__*/createReactComponent<JSX.ElsaButtonGroup, HTMLElsaButtonGroupElement>('elsa-button-group');
export const ElsaCheckList = /*@__PURE__*/createReactComponent<JSX.ElsaCheckList, HTMLElsaCheckListElement>('elsa-check-list');
export const ElsaCheckListInput = /*@__PURE__*/createReactComponent<JSX.ElsaCheckListInput, HTMLElsaCheckListInputElement>('elsa-check-list-input');
export const ElsaCheckboxInput = /*@__PURE__*/createReactComponent<JSX.ElsaCheckboxInput, HTMLElsaCheckboxInputElement>('elsa-checkbox-input');
export const ElsaCodeEditorInput = /*@__PURE__*/createReactComponent<JSX.ElsaCodeEditorInput, HTMLElsaCodeEditorInputElement>('elsa-code-editor-input');
export const ElsaContextMenu = /*@__PURE__*/createReactComponent<JSX.ElsaContextMenu, HTMLElsaContextMenuElement>('elsa-context-menu');
export const ElsaCopyButton = /*@__PURE__*/createReactComponent<JSX.ElsaCopyButton, HTMLElsaCopyButtonElement>('elsa-copy-button');
export const ElsaDefaultActivityTemplate = /*@__PURE__*/createReactComponent<JSX.ElsaDefaultActivityTemplate, HTMLElsaDefaultActivityTemplateElement>('elsa-default-activity-template');
export const ElsaDropdownButton = /*@__PURE__*/createReactComponent<JSX.ElsaDropdownButton, HTMLElsaDropdownButtonElement>('elsa-dropdown-button');
export const ElsaDropdownInput = /*@__PURE__*/createReactComponent<JSX.ElsaDropdownInput, HTMLElsaDropdownInputElement>('elsa-dropdown-input');
export const ElsaFlowSwitchEditor = /*@__PURE__*/createReactComponent<JSX.ElsaFlowSwitchEditor, HTMLElsaFlowSwitchEditorElement>('elsa-flow-switch-editor');
export const ElsaFlowchart = /*@__PURE__*/createReactComponent<JSX.ElsaFlowchart, HTMLElsaFlowchartElement>('elsa-flowchart');
export const ElsaFormPanel = /*@__PURE__*/createReactComponent<JSX.ElsaFormPanel, HTMLElsaFormPanelElement>('elsa-form-panel');
export const ElsaHomePage = /*@__PURE__*/createReactComponent<JSX.ElsaHomePage, HTMLElsaHomePageElement>('elsa-home-page');
export const ElsaHttpStatusCodesEditor = /*@__PURE__*/createReactComponent<JSX.ElsaHttpStatusCodesEditor, HTMLElsaHttpStatusCodesEditorElement>('elsa-http-status-codes-editor');
export const ElsaInputControlSwitch = /*@__PURE__*/createReactComponent<JSX.ElsaInputControlSwitch, HTMLElsaInputControlSwitchElement>('elsa-input-control-switch');
export const ElsaInputTags = /*@__PURE__*/createReactComponent<JSX.ElsaInputTags, HTMLElsaInputTagsElement>('elsa-input-tags');
export const ElsaInputTagsDropdown = /*@__PURE__*/createReactComponent<JSX.ElsaInputTagsDropdown, HTMLElsaInputTagsDropdownElement>('elsa-input-tags-dropdown');
export const ElsaLabelPicker = /*@__PURE__*/createReactComponent<JSX.ElsaLabelPicker, HTMLElsaLabelPickerElement>('elsa-label-picker');
export const ElsaLoginPage = /*@__PURE__*/createReactComponent<JSX.ElsaLoginPage, HTMLElsaLoginPageElement>('elsa-login-page');
export const ElsaModalDialog = /*@__PURE__*/createReactComponent<JSX.ElsaModalDialog, HTMLElsaModalDialogElement>('elsa-modal-dialog');
export const ElsaModalDialogContainer = /*@__PURE__*/createReactComponent<JSX.ElsaModalDialogContainer, HTMLElsaModalDialogContainerElement>('elsa-modal-dialog-container');
export const ElsaMonacoEditor = /*@__PURE__*/createReactComponent<JSX.ElsaMonacoEditor, HTMLElsaMonacoEditorElement>('elsa-monaco-editor');
export const ElsaMultiLineInput = /*@__PURE__*/createReactComponent<JSX.ElsaMultiLineInput, HTMLElsaMultiLineInputElement>('elsa-multi-line-input');
export const ElsaMultiTextInput = /*@__PURE__*/createReactComponent<JSX.ElsaMultiTextInput, HTMLElsaMultiTextInputElement>('elsa-multi-text-input');
export const ElsaNotificationTemplate = /*@__PURE__*/createReactComponent<JSX.ElsaNotificationTemplate, HTMLElsaNotificationTemplateElement>('elsa-notification-template');
export const ElsaNotificationsManager = /*@__PURE__*/createReactComponent<JSX.ElsaNotificationsManager, HTMLElsaNotificationsManagerElement>('elsa-notifications-manager');
export const ElsaOutcomePickerInput = /*@__PURE__*/createReactComponent<JSX.ElsaOutcomePickerInput, HTMLElsaOutcomePickerInputElement>('elsa-outcome-picker-input');
export const ElsaOutputPickerInput = /*@__PURE__*/createReactComponent<JSX.ElsaOutputPickerInput, HTMLElsaOutputPickerInputElement>('elsa-output-picker-input');
export const ElsaPager = /*@__PURE__*/createReactComponent<JSX.ElsaPager, HTMLElsaPagerElement>('elsa-pager');
export const ElsaPanel = /*@__PURE__*/createReactComponent<JSX.ElsaPanel, HTMLElsaPanelElement>('elsa-panel');
export const ElsaRadioListInput = /*@__PURE__*/createReactComponent<JSX.ElsaRadioListInput, HTMLElsaRadioListInputElement>('elsa-radio-list-input');
export const ElsaShell = /*@__PURE__*/createReactComponent<JSX.ElsaShell, HTMLElsaShellElement>('elsa-shell');
export const ElsaSingleLineInput = /*@__PURE__*/createReactComponent<JSX.ElsaSingleLineInput, HTMLElsaSingleLineInputElement>('elsa-single-line-input');
export const ElsaSlideOverPanel = /*@__PURE__*/createReactComponent<JSX.ElsaSlideOverPanel, HTMLElsaSlideOverPanelElement>('elsa-slide-over-panel');
export const ElsaStudio = /*@__PURE__*/createReactComponent<JSX.ElsaStudio, HTMLElsaStudioElement>('elsa-studio');
export const ElsaSwitchEditor = /*@__PURE__*/createReactComponent<JSX.ElsaSwitchEditor, HTMLElsaSwitchEditorElement>('elsa-switch-editor');
export const ElsaToastManager = /*@__PURE__*/createReactComponent<JSX.ElsaToastManager, HTMLElsaToastManagerElement>('elsa-toast-manager');
export const ElsaToastNotification = /*@__PURE__*/createReactComponent<JSX.ElsaToastNotification, HTMLElsaToastNotificationElement>('elsa-toast-notification');
export const ElsaTooltip = /*@__PURE__*/createReactComponent<JSX.ElsaTooltip, HTMLElsaTooltipElement>('elsa-tooltip');
export const ElsaTypePickerInput = /*@__PURE__*/createReactComponent<JSX.ElsaTypePickerInput, HTMLElsaTypePickerInputElement>('elsa-type-picker-input');
export const ElsaVariableEditorDialogContent = /*@__PURE__*/createReactComponent<JSX.ElsaVariableEditorDialogContent, HTMLElsaVariableEditorDialogContentElement>('elsa-variable-editor-dialog-content');
export const ElsaVariablePickerInput = /*@__PURE__*/createReactComponent<JSX.ElsaVariablePickerInput, HTMLElsaVariablePickerInputElement>('elsa-variable-picker-input');
export const ElsaVariablesEditor = /*@__PURE__*/createReactComponent<JSX.ElsaVariablesEditor, HTMLElsaVariablesEditorElement>('elsa-variables-editor');
export const ElsaVariablesViewer = /*@__PURE__*/createReactComponent<JSX.ElsaVariablesViewer, HTMLElsaVariablesViewerElement>('elsa-variables-viewer');
export const ElsaWidgets = /*@__PURE__*/createReactComponent<JSX.ElsaWidgets, HTMLElsaWidgetsElement>('elsa-widgets');
export const ElsaWorkflowContextProviderCheckList = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowContextProviderCheckList, HTMLElsaWorkflowContextProviderCheckListElement>('elsa-workflow-context-provider-check-list');
export const ElsaWorkflowContextProviderTypePickerInput = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowContextProviderTypePickerInput, HTMLElsaWorkflowContextProviderTypePickerInputElement>('elsa-workflow-context-provider-type-picker-input');
export const ElsaWorkflowDefinitionActivityVersionSettings = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionActivityVersionSettings, HTMLElsaWorkflowDefinitionActivityVersionSettingsElement>('elsa-workflow-definition-activity-version-settings');
export const ElsaWorkflowDefinitionBrowser = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionBrowser, HTMLElsaWorkflowDefinitionBrowserElement>('elsa-workflow-definition-browser');
export const ElsaWorkflowDefinitionEditor = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionEditor, HTMLElsaWorkflowDefinitionEditorElement>('elsa-workflow-definition-editor');
export const ElsaWorkflowDefinitionEditorToolbar = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionEditorToolbar, HTMLElsaWorkflowDefinitionEditorToolbarElement>('elsa-workflow-definition-editor-toolbar');
export const ElsaWorkflowDefinitionEditorToolbox = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionEditorToolbox, HTMLElsaWorkflowDefinitionEditorToolboxElement>('elsa-workflow-definition-editor-toolbox');
export const ElsaWorkflowDefinitionEditorToolboxActivities = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionEditorToolboxActivities, HTMLElsaWorkflowDefinitionEditorToolboxActivitiesElement>('elsa-workflow-definition-editor-toolbox-activities');
export const ElsaWorkflowDefinitionInputOutputSettings = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionInputOutputSettings, HTMLElsaWorkflowDefinitionInputOutputSettingsElement>('elsa-workflow-definition-input-output-settings');
export const ElsaWorkflowDefinitionPickerInput = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionPickerInput, HTMLElsaWorkflowDefinitionPickerInputElement>('elsa-workflow-definition-picker-input');
export const ElsaWorkflowDefinitionPropertiesEditor = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionPropertiesEditor, HTMLElsaWorkflowDefinitionPropertiesEditorElement>('elsa-workflow-definition-properties-editor');
export const ElsaWorkflowDefinitionVersionHistory = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowDefinitionVersionHistory, HTMLElsaWorkflowDefinitionVersionHistoryElement>('elsa-workflow-definition-version-history');
export const ElsaWorkflowInstanceBrowser = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowInstanceBrowser, HTMLElsaWorkflowInstanceBrowserElement>('elsa-workflow-instance-browser');
export const ElsaWorkflowInstanceProperties = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowInstanceProperties, HTMLElsaWorkflowInstancePropertiesElement>('elsa-workflow-instance-properties');
export const ElsaWorkflowInstanceViewer = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowInstanceViewer, HTMLElsaWorkflowInstanceViewerElement>('elsa-workflow-instance-viewer');
export const ElsaWorkflowJournal = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowJournal, HTMLElsaWorkflowJournalElement>('elsa-workflow-journal');
export const ElsaWorkflowNavigator = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowNavigator, HTMLElsaWorkflowNavigatorElement>('elsa-workflow-navigator');
export const ElsaWorkflowPublishButton = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowPublishButton, HTMLElsaWorkflowPublishButtonElement>('elsa-workflow-publish-button');
export const ElsaWorkflowToolbar = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowToolbar, HTMLElsaWorkflowToolbarElement>('elsa-workflow-toolbar');
export const ElsaWorkflowToolbarMenu = /*@__PURE__*/createReactComponent<JSX.ElsaWorkflowToolbarMenu, HTMLElsaWorkflowToolbarMenuElement>('elsa-workflow-toolbar-menu');
