apiVersion: v1
kind: Service
metadata:
  name: elsa-studio-service
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 9001
      targetPort: 8080
  selector:
    app: elsa-studio
