<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Include>[Elsa.Connections]*</Include>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\modules\Elsa.Connections\Elsa.Connections.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Connections.Persistence.EFCore.Sqlite\Elsa.Connections.Persistence.EFCore.Sqlite.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Secrets.Persistence.EFCore.Sqlite\Elsa.Secrets.Persistence.EFCore.Sqlite.csproj" />
    </ItemGroup>
</Project>
