<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Include>[Elsa.Connections]*</Include>
        <Threshold>0</Threshold>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Testcontainers.PostgreSql" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Connections.Credentials.Persistence.EFCore.PostgreSql\Elsa.Connections.Credentials.Persistence.EFCore.PostgreSql.csproj" />
        <ProjectReference Include="..\..\workers\Elsa.Connections.Credentials.WorkerProcess\Elsa.Connections.Credentials.WorkerProcess.csproj" />
    </ItemGroup>

</Project>
