<Project><Import Project="../../build/ConsolidatedPackageProof.targets" /><PropertyGroup><UseProjectReferences>true</UseProjectReferences><IsPackable Condition="'$(ConsolidatedPackageProof)' != 'true'">false</IsPackable><GeneratePackageOnBuild>false</GeneratePackageOnBuild></PropertyGroup></Project>
