<Project>
    <PropertyGroup>
        <Authors>Elsa Workflows Community</Authors>
        <Copyright>2025</Copyright>

        <PackageProjectUrl>https://github.com/elsa-workflows/elsa-extensions</PackageProjectUrl>
        <RepositoryUrl>https://github.com/elsa-workflows/elsa-extensions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>

        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>

        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>

        <!-- For NuGet browsers that currently don't support <PackageIcon> yet -->
        <PackageIconUrl>https://v3.elsaworkflows.io/nuget-icon.png</PackageIconUrl>

        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AnalysisModeDocumentation>Default</AnalysisModeDocumentation>
        <AnalysisLevelDocumentation>latest</AnalysisLevelDocumentation>

		<NuGetAudit>enable</NuGetAudit>
		<NuGetAuditMode>all</NuGetAuditMode>

        <!-- https://github.com/dotnet/sourcelink -->
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup>
		<NoWarn>$(NoWarn);CS0162;CS1591</NoWarn>
		<!-- IL trimming warnings -->
		<NoWarn>$(NoWarn);IL2026;IL2046;IL2057;IL2067;IL2070;IL2072;IL2075;IL2087;IL2091</NoWarn>
	</PropertyGroup>

    <PropertyGroup Label="PackageVersions">
        <ElsaVersion>3.8.0-preview.5557</ElsaVersion>
        <ElsaStudioVersion>3.8.0</ElsaStudioVersion>
    </PropertyGroup>





  <PropertyGroup Label="TargetFrameworks">
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Label="Files">
    <None Include="..\..\..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ConfigureAwait.Fody" PrivateAssets="All" />
    <PackageReference Include="Fody" PrivateAssets="All" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Condition="Exists('$(MSBuildProjectDirectory)/ShellFeatures')">
    <PackageReference Include="Elsa.Platform.PackageManifest.Generator" PrivateAssets="all" />
    <Compile Include="$(MSBuildThisFileDirectory)PackageManifestHints.cs" Link="PackageManifestHints.cs" />
  </ItemGroup>

<PropertyGroup><UseProjectReferences>true</UseProjectReferences><IsPackable>false</IsPackable></PropertyGroup></Project>
