<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Elsa.Secrets.Persistence.EFCore" Version="[3.8.1]" />
    <PackageReference Include="Elsa.Secrets.Persistence.EFCore.Sqlite" Version="[3.8.1]" />
    <Compile Include="../shared/LegacySecretsConsumer.cs" Link="LegacySecretsConsumer.cs" />
  </ItemGroup>
</Project>
