<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="../../../../../src/common/Elsa.Testing.Shared/Elsa.Testing.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../../../../../src/extensions/ldap/Elsa.Ldap/Elsa.Ldap.csproj" />
	</ItemGroup>

</Project>
