<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\src\modules\actors\Elsa.Actors.ProtoActor\Elsa.Actors.ProtoActor.csproj" />
        <ProjectReference Include="..\..\..\..\src\modules\actors\Elsa.Actors.ProtoActor.PubSub.Redis\Elsa.Actors.ProtoActor.PubSub.Redis.csproj" />
        <ProjectReference Include="..\..\..\..\src\modules\caching\Elsa.Caching.Distributed.ProtoActor\Elsa.Caching.Distributed.ProtoActor.csproj" />
    </ItemGroup>

</Project>
