<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Include>[Elsa.Alterations.Core]*</Include>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\common\Elsa.Testing.Shared\Elsa.Testing.Shared.csproj" />
        <ProjectReference Include="..\..\..\src\modules\Elsa.Alterations.Core\Elsa.Alterations.Core.csproj" />
    </ItemGroup>

</Project>
