/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InputDefinition, OutputDefinition, WorkflowDefinition, WorkflowDefinitionSummary } from "./modules/workflow-definitions/models/entities";
import { Activity, ActivityDeletedArgs, ActivitySelectedArgs, ChildActivitySelectedArgs, ContainerSelectedArgs, EditChildActivityArgs, GraphUpdatedArgs, IntellisenseContext, SelectList, SelectListItem, TabChangedArgs, TabDefinition, Variable, WorkflowExecutionLogRecord, WorkflowInstance, WorkflowInstanceSummary, WorkflowUpdatedArgs } from "./models";
import { ActivityUpdatedArgs, DeleteActivityRequestedArgs, Widget, WorkflowDefinitionPropsUpdatedArgs, WorkflowDefinitionUpdatedArgs } from "./modules/workflow-definitions/models/ui";
import { Button } from "./components/shared/button-group/models";
import { ActivityInputContext } from "./services/activity-input-driver";
import { ContextMenuAnchorPoint, ContextMenuItem } from "./components/shared/context-menu/models";
import { DropdownButtonItem, DropdownButtonOrigin } from "./components/shared/dropdown-button/models";
import { Graph } from "@antv/x6";
import { AddActivityArgs, FlowchartPathItem, LayoutDirection, RenameActivityArgs, UpdateActivityArgs } from "./modules/flowchart/models";
import { OutNode } from "@antv/layout";
import { ActivityNodeShape } from "./modules/flowchart/shapes";
import { PanelActionClickArgs, PanelActionDefinition } from "./components/shared/form-panel/models";
import { ExpressionChangedArs } from "./components/shared/input-control-switch/input-control-switch";
import { SignedInArgs } from "./modules/login/models";
import { ModalActionClickArgs, ModalActionDefinition, ModalDialogInstance } from "./components/shared/modal-dialog/models";
import { ModalType } from "./components/shared/modal-dialog/modal-type";
import { MonacoValueChangedArgs } from "./components/shared/monaco-editor/monaco-editor";
import { NotificationType } from "./modules/notifications/models";
import { PagerData } from "./components/shared/pager/pager";
import { PanelPosition, PanelStateChangedArgs } from "./components/panel/models";
import { ShellInitializingContext } from "./models/shell";
import { WorkflowContextProviderDescriptor } from "./modules/workflow-contexts/services/api";
import { RenderActivityPropsContext } from "./modules/workflow-definitions/components/models";
import { ActivityDriverRegistry } from "./services";
import { JournalItemSelectedArgs } from "./modules/workflow-instances/events";
import { PublishClickedArgs } from "./modules/workflow-definitions/components/publish-button";
export namespace Components {
    interface ElsaActivityInputEditorDialogContent {
        "getInput": () => Promise<InputDefinition>;
        "input": InputDefinition;
    }
    interface ElsaActivityOutputEditorDialogContent {
        "getOutput": () => Promise<OutputDefinition>;
        "output": OutputDefinition;
    }
    interface ElsaActivityProperties {
        "activity"?: Activity;
        "activityExecutionLog": WorkflowExecutionLogRecord;
        "activityPropertyTabIndex"?: number;
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
        "updateSelectedTab": (tabIndex: number) => Promise<void>;
    }
    interface ElsaActivityPropertiesEditor {
        "activity"?: Activity;
        "hide": () => Promise<void>;
        "outputs": Array<OutputDefinition>;
        "show": () => Promise<void>;
        "variables": Array<Variable>;
        "workflowDefinitionId": string;
    }
    interface ElsaBlank {
    }
    interface ElsaButtonGroup {
        "buttons": Array<Button>;
    }
    interface ElsaCheckList {
        "fieldName": string;
        "selectList": SelectList;
        "selectedValue"?: number;
        "selectedValues"?: Array<string>;
    }
    interface ElsaCheckListInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaCheckboxInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaCodeEditorInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaContextMenu {
        "anchorPoint": ContextMenuAnchorPoint;
        "close": () => Promise<void>;
        "hideButton": boolean;
        "menuItems": Array<ContextMenuItem>;
        "open": () => Promise<void>;
    }
    interface ElsaCopyButton {
        "value": string;
    }
    interface ElsaDefaultActivityTemplate {
        "activityId": string;
        "activityType": string;
        "activityTypeVersion": number;
        "displayType": string;
    }
    interface ElsaDropdownButton {
        "handler"?: () => void;
        "icon"?: any;
        "items": Array<DropdownButtonItem>;
        "origin": DropdownButtonOrigin;
        "text": string;
        "theme": ('Primary' | 'Secondary');
    }
    interface ElsaDropdownInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaFlowSwitchEditor {
        "inputContext": ActivityInputContext;
    }
    interface ElsaFlowchart {
        "addActivity": (args: AddActivityArgs) => Promise<Activity>;
        "autoLayout": (direction: LayoutDirection) => Promise<void>;
        "export": () => Promise<Activity>;
        "getActivity": (id: string) => Promise<Activity>;
        "getGraph": () => Promise<Graph>;
        "interactiveMode": boolean;
        "newRoot": () => Promise<Activity>;
        "renameActivity": (args: RenameActivityArgs) => Promise<void>;
        "reset": () => Promise<void>;
        "rootActivity": Activity;
        "scrollToStart": () => Promise<void>;
        "silent": boolean;
        "updateActivity": (args: UpdateActivityArgs) => Promise<void>;
        "updateGraph": () => Promise<void>;
        "updateLayout": () => Promise<void>;
        "zoomToFit": () => Promise<void>;
    }
    interface ElsaFormPanel {
        "actions": Array<PanelActionDefinition>;
        "mainTitle": string;
        "orientation": 'Landscape' | 'Portrait';
        "selectedTabIndex"?: number;
        "subTitle": string;
        "tabs": Array<TabDefinition>;
    }
    interface ElsaHomePage {
    }
    interface ElsaHttpStatusCodesEditor {
        "inputContext": ActivityInputContext;
    }
    interface ElsaInputControlSwitch {
        "activityType": string;
        "codeEditorHeight": string;
        "codeEditorSingleLineMode": boolean;
        "context"?: IntellisenseContext;
        "defaultSyntax": string;
        "expression"?: string;
        "fieldName"?: string;
        "hideLabel": boolean;
        "hint": string;
        "isReadOnly"?: boolean;
        "label": string;
        "propertyName": string;
        "supportedSyntaxes": Array<string>;
        "syntax"?: string;
        "workflowDefinitionId": string;
    }
    interface ElsaInputTags {
        "fieldId"?: string;
        "placeHolder"?: string;
        "values"?: Array<string>;
    }
    interface ElsaInputTagsDropdown {
        "dropdownValues"?: Array<SelectListItem>;
        "fieldId"?: string;
        "fieldName"?: string;
        "placeHolder"?: string;
        "values"?: Array<string | SelectListItem>;
    }
    interface ElsaLabelPicker {
        "buttonClass"?: string;
        "containerClass"?: string;
        "selectedLabels": Array<string>;
    }
    interface ElsaLoginPage {
    }
    interface ElsaModalDialog {
        "actions": Array<ModalActionDefinition>;
        "autoHide": boolean;
        "content": () => any;
        "hide": (animate?: boolean) => Promise<void>;
        "modalDialogInstance": ModalDialogInstance;
        "show": (animate?: boolean) => Promise<void>;
        "size": string;
        "type": ModalType;
    }
    interface ElsaModalDialogContainer {
    }
    interface ElsaMonacoEditor {
        "addJavaScriptLib": (libSource: string, libUri: string) => Promise<void>;
        "editorHeight": string;
        "language": string;
        "padding": string;
        "setValue": (value: string) => Promise<void>;
        "singleLineMode": boolean;
        "value": string;
    }
    interface ElsaMultiLineInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaMultiTextInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaNotificationTemplate {
        "notification": NotificationType;
    }
    interface ElsaNotificationsManager {
        "modalState": boolean;
    }
    interface ElsaOutcomePickerInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaOutputPickerInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaPager {
        "page": number;
        "pageSize": number;
        "totalCount": number;
    }
    interface ElsaPanel {
        "position": PanelPosition;
    }
    interface ElsaRadioListInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaShell {
    }
    interface ElsaSingleLineInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaSlideOverPanel {
        "actions": Array<PanelActionDefinition>;
        "expand": boolean;
        "headerText": string;
        "hide": () => Promise<void>;
        "selectedTab"?: TabDefinition;
        "show": () => Promise<void>;
        "tabs": Array<TabDefinition>;
    }
    interface ElsaStudio {
        "enableFlexiblePorts": boolean;
        "monacoLibPath": string;
        "serverUrl": string;
    }
    interface ElsaSwitchEditor {
        "inputContext": ActivityInputContext;
    }
    interface ElsaToastManager {
    }
    interface ElsaToastNotification {
        "notification": NotificationType;
        "showDuration": number;
    }
    interface ElsaTooltip {
        "tooltipContent": any;
        /**
          * Specifying `auto` will default to `bottom`, but will reposition to `top` if the tooltip height runs offscreen
         */
        "tooltipPosition"?: 'right' | 'left' | 'top' | 'bottom' | 'auto';
    }
    interface ElsaTypePickerInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaVariableEditorDialogContent {
        "getVariable": () => Promise<Variable>;
        "variable": Variable;
    }
    interface ElsaVariablePickerInput {
        "inputContext": ActivityInputContext;
        "workflowDefinition": WorkflowDefinition;
    }
    interface ElsaVariablesEditor {
        "variables"?: Array<Variable>;
    }
    interface ElsaVariablesViewer {
        "variables"?: Array<Variable>;
        "workflowDefinition": WorkflowDefinition;
        "workflowInstance": WorkflowInstance;
    }
    interface ElsaWidgets {
        "widgets": Array<Widget>;
    }
    interface ElsaWorkflowContextProviderCheckList {
        "descriptors": Array<WorkflowContextProviderDescriptor>;
        "workflowDefinition": WorkflowDefinition;
    }
    interface ElsaWorkflowContextProviderTypePickerInput {
        "descriptors": Array<WorkflowContextProviderDescriptor>;
        "inputContext": ActivityInputContext;
        "workflowDefinition": WorkflowDefinition;
    }
    interface ElsaWorkflowDefinitionActivityVersionSettings {
        "renderContext": RenderActivityPropsContext;
    }
    interface ElsaWorkflowDefinitionBrowser {
    }
    interface ElsaWorkflowDefinitionEditor {
        "getFlowchart": () => Promise<HTMLElsaFlowchartElement>;
        "getWorkflowDefinition": () => Promise<WorkflowDefinition>;
        "importWorkflow": (workflowDefinition: WorkflowDefinition) => Promise<void>;
        "loadWorkflowVersions": () => Promise<void>;
        "monacoLibPath": string;
        "newWorkflow": () => Promise<WorkflowDefinition>;
        "registerActivityDrivers": (register: (registry: ActivityDriverRegistry) => void) => Promise<void>;
        "updateActivity": (activity: Activity) => Promise<void>;
        "updateWorkflowDefinition": (workflowDefinition: WorkflowDefinition) => Promise<void>;
        "workflowDefinition"?: WorkflowDefinition;
    }
    interface ElsaWorkflowDefinitionEditorToolbar {
        "zoomToFit": () => Promise<void>;
    }
    interface ElsaWorkflowDefinitionEditorToolbox {
        "graph": Graph;
    }
    interface ElsaWorkflowDefinitionEditorToolboxActivities {
        "graph": Graph;
    }
    interface ElsaWorkflowDefinitionInputOutputSettings {
        "inputs"?: Array<InputDefinition>;
        "outcomes"?: Array<string>;
        "outputs"?: Array<OutputDefinition>;
    }
    interface ElsaWorkflowDefinitionPickerInput {
        "inputContext": ActivityInputContext;
    }
    interface ElsaWorkflowDefinitionPropertiesEditor {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
        "workflowDefinition"?: WorkflowDefinition;
        "workflowVersions": Array<WorkflowDefinition>;
    }
    interface ElsaWorkflowDefinitionVersionHistory {
        "selectedVersion": WorkflowDefinition;
        "serverUrl": string;
        "workflowVersions": Array<WorkflowDefinition>;
    }
    interface ElsaWorkflowInstanceBrowser {
    }
    interface ElsaWorkflowInstanceProperties {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
        "workflowDefinition"?: WorkflowDefinition;
        "workflowInstance"?: WorkflowInstance;
    }
    interface ElsaWorkflowInstanceViewer {
        "getCanvas": () => Promise<HTMLElsaFlowchartElement>;
        "getWorkflow": () => Promise<WorkflowDefinition>;
        "importWorkflow": (workflowDefinition: WorkflowDefinition, workflowInstance: WorkflowInstance) => Promise<void>;
        "monacoLibPath": string;
        "registerActivityDrivers": (register: (registry: ActivityDriverRegistry) => void) => Promise<void>;
        "updateWorkflowDefinition": (workflowDefinition: WorkflowDefinition) => Promise<void>;
        "workflowDefinition": WorkflowDefinition;
        "workflowInstance": WorkflowInstance;
    }
    interface ElsaWorkflowJournal {
        "workflowDefinition": WorkflowDefinition;
        "workflowInstance": WorkflowInstance;
    }
    interface ElsaWorkflowNavigator {
        "items": Array<FlowchartPathItem>;
        "rootActivity": Activity;
    }
    interface ElsaWorkflowPublishButton {
        "publishing": boolean;
    }
    interface ElsaWorkflowToolbar {
    }
    interface ElsaWorkflowToolbarMenu {
    }
}
export interface ElsaActivityInputEditorDialogContentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaActivityInputEditorDialogContentElement;
}
export interface ElsaActivityOutputEditorDialogContentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaActivityOutputEditorDialogContentElement;
}
export interface ElsaActivityPropertiesEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaActivityPropertiesEditorElement;
}
export interface ElsaCheckListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaCheckListElement;
}
export interface ElsaDefaultActivityTemplateCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaDefaultActivityTemplateElement;
}
export interface ElsaDropdownButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaDropdownButtonElement;
}
export interface ElsaFlowchartCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaFlowchartElement;
}
export interface ElsaFormPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaFormPanelElement;
}
export interface ElsaInputControlSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaInputControlSwitchElement;
}
export interface ElsaInputTagsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaInputTagsElement;
}
export interface ElsaInputTagsDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaInputTagsDropdownElement;
}
export interface ElsaLabelPickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaLabelPickerElement;
}
export interface ElsaLoginPageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaLoginPageElement;
}
export interface ElsaModalDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaModalDialogElement;
}
export interface ElsaMonacoEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaMonacoEditorElement;
}
export interface ElsaPagerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaPagerElement;
}
export interface ElsaPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaPanelElement;
}
export interface ElsaShellCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaShellElement;
}
export interface ElsaSlideOverPanelCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaSlideOverPanelElement;
}
export interface ElsaVariableEditorDialogContentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaVariableEditorDialogContentElement;
}
export interface ElsaVariablesEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaVariablesEditorElement;
}
export interface ElsaWorkflowContextProviderCheckListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowContextProviderCheckListElement;
}
export interface ElsaWorkflowDefinitionBrowserCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowDefinitionBrowserElement;
}
export interface ElsaWorkflowDefinitionEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowDefinitionEditorElement;
}
export interface ElsaWorkflowDefinitionEditorToolbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowDefinitionEditorToolbarElement;
}
export interface ElsaWorkflowDefinitionInputOutputSettingsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowDefinitionInputOutputSettingsElement;
}
export interface ElsaWorkflowDefinitionPropertiesEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowDefinitionPropertiesEditorElement;
}
export interface ElsaWorkflowDefinitionVersionHistoryCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowDefinitionVersionHistoryElement;
}
export interface ElsaWorkflowInstanceBrowserCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowInstanceBrowserElement;
}
export interface ElsaWorkflowJournalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowJournalElement;
}
export interface ElsaWorkflowNavigatorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowNavigatorElement;
}
export interface ElsaWorkflowPublishButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLElsaWorkflowPublishButtonElement;
}
declare global {
    interface HTMLElsaActivityInputEditorDialogContentElement extends Components.ElsaActivityInputEditorDialogContent, HTMLStencilElement {
    }
    var HTMLElsaActivityInputEditorDialogContentElement: {
        prototype: HTMLElsaActivityInputEditorDialogContentElement;
        new (): HTMLElsaActivityInputEditorDialogContentElement;
    };
    interface HTMLElsaActivityOutputEditorDialogContentElement extends Components.ElsaActivityOutputEditorDialogContent, HTMLStencilElement {
    }
    var HTMLElsaActivityOutputEditorDialogContentElement: {
        prototype: HTMLElsaActivityOutputEditorDialogContentElement;
        new (): HTMLElsaActivityOutputEditorDialogContentElement;
    };
    interface HTMLElsaActivityPropertiesElement extends Components.ElsaActivityProperties, HTMLStencilElement {
    }
    var HTMLElsaActivityPropertiesElement: {
        prototype: HTMLElsaActivityPropertiesElement;
        new (): HTMLElsaActivityPropertiesElement;
    };
    interface HTMLElsaActivityPropertiesEditorElement extends Components.ElsaActivityPropertiesEditor, HTMLStencilElement {
    }
    var HTMLElsaActivityPropertiesEditorElement: {
        prototype: HTMLElsaActivityPropertiesEditorElement;
        new (): HTMLElsaActivityPropertiesEditorElement;
    };
    interface HTMLElsaBlankElement extends Components.ElsaBlank, HTMLStencilElement {
    }
    var HTMLElsaBlankElement: {
        prototype: HTMLElsaBlankElement;
        new (): HTMLElsaBlankElement;
    };
    interface HTMLElsaButtonGroupElement extends Components.ElsaButtonGroup, HTMLStencilElement {
    }
    var HTMLElsaButtonGroupElement: {
        prototype: HTMLElsaButtonGroupElement;
        new (): HTMLElsaButtonGroupElement;
    };
    interface HTMLElsaCheckListElement extends Components.ElsaCheckList, HTMLStencilElement {
    }
    var HTMLElsaCheckListElement: {
        prototype: HTMLElsaCheckListElement;
        new (): HTMLElsaCheckListElement;
    };
    interface HTMLElsaCheckListInputElement extends Components.ElsaCheckListInput, HTMLStencilElement {
    }
    var HTMLElsaCheckListInputElement: {
        prototype: HTMLElsaCheckListInputElement;
        new (): HTMLElsaCheckListInputElement;
    };
    interface HTMLElsaCheckboxInputElement extends Components.ElsaCheckboxInput, HTMLStencilElement {
    }
    var HTMLElsaCheckboxInputElement: {
        prototype: HTMLElsaCheckboxInputElement;
        new (): HTMLElsaCheckboxInputElement;
    };
    interface HTMLElsaCodeEditorInputElement extends Components.ElsaCodeEditorInput, HTMLStencilElement {
    }
    var HTMLElsaCodeEditorInputElement: {
        prototype: HTMLElsaCodeEditorInputElement;
        new (): HTMLElsaCodeEditorInputElement;
    };
    interface HTMLElsaContextMenuElement extends Components.ElsaContextMenu, HTMLStencilElement {
    }
    var HTMLElsaContextMenuElement: {
        prototype: HTMLElsaContextMenuElement;
        new (): HTMLElsaContextMenuElement;
    };
    interface HTMLElsaCopyButtonElement extends Components.ElsaCopyButton, HTMLStencilElement {
    }
    var HTMLElsaCopyButtonElement: {
        prototype: HTMLElsaCopyButtonElement;
        new (): HTMLElsaCopyButtonElement;
    };
    interface HTMLElsaDefaultActivityTemplateElement extends Components.ElsaDefaultActivityTemplate, HTMLStencilElement {
    }
    var HTMLElsaDefaultActivityTemplateElement: {
        prototype: HTMLElsaDefaultActivityTemplateElement;
        new (): HTMLElsaDefaultActivityTemplateElement;
    };
    interface HTMLElsaDropdownButtonElement extends Components.ElsaDropdownButton, HTMLStencilElement {
    }
    var HTMLElsaDropdownButtonElement: {
        prototype: HTMLElsaDropdownButtonElement;
        new (): HTMLElsaDropdownButtonElement;
    };
    interface HTMLElsaDropdownInputElement extends Components.ElsaDropdownInput, HTMLStencilElement {
    }
    var HTMLElsaDropdownInputElement: {
        prototype: HTMLElsaDropdownInputElement;
        new (): HTMLElsaDropdownInputElement;
    };
    interface HTMLElsaFlowSwitchEditorElement extends Components.ElsaFlowSwitchEditor, HTMLStencilElement {
    }
    var HTMLElsaFlowSwitchEditorElement: {
        prototype: HTMLElsaFlowSwitchEditorElement;
        new (): HTMLElsaFlowSwitchEditorElement;
    };
    interface HTMLElsaFlowchartElement extends Components.ElsaFlowchart, HTMLStencilElement {
    }
    var HTMLElsaFlowchartElement: {
        prototype: HTMLElsaFlowchartElement;
        new (): HTMLElsaFlowchartElement;
    };
    interface HTMLElsaFormPanelElement extends Components.ElsaFormPanel, HTMLStencilElement {
    }
    var HTMLElsaFormPanelElement: {
        prototype: HTMLElsaFormPanelElement;
        new (): HTMLElsaFormPanelElement;
    };
    interface HTMLElsaHomePageElement extends Components.ElsaHomePage, HTMLStencilElement {
    }
    var HTMLElsaHomePageElement: {
        prototype: HTMLElsaHomePageElement;
        new (): HTMLElsaHomePageElement;
    };
    interface HTMLElsaHttpStatusCodesEditorElement extends Components.ElsaHttpStatusCodesEditor, HTMLStencilElement {
    }
    var HTMLElsaHttpStatusCodesEditorElement: {
        prototype: HTMLElsaHttpStatusCodesEditorElement;
        new (): HTMLElsaHttpStatusCodesEditorElement;
    };
    interface HTMLElsaInputControlSwitchElement extends Components.ElsaInputControlSwitch, HTMLStencilElement {
    }
    var HTMLElsaInputControlSwitchElement: {
        prototype: HTMLElsaInputControlSwitchElement;
        new (): HTMLElsaInputControlSwitchElement;
    };
    interface HTMLElsaInputTagsElement extends Components.ElsaInputTags, HTMLStencilElement {
    }
    var HTMLElsaInputTagsElement: {
        prototype: HTMLElsaInputTagsElement;
        new (): HTMLElsaInputTagsElement;
    };
    interface HTMLElsaInputTagsDropdownElement extends Components.ElsaInputTagsDropdown, HTMLStencilElement {
    }
    var HTMLElsaInputTagsDropdownElement: {
        prototype: HTMLElsaInputTagsDropdownElement;
        new (): HTMLElsaInputTagsDropdownElement;
    };
    interface HTMLElsaLabelPickerElement extends Components.ElsaLabelPicker, HTMLStencilElement {
    }
    var HTMLElsaLabelPickerElement: {
        prototype: HTMLElsaLabelPickerElement;
        new (): HTMLElsaLabelPickerElement;
    };
    interface HTMLElsaLoginPageElement extends Components.ElsaLoginPage, HTMLStencilElement {
    }
    var HTMLElsaLoginPageElement: {
        prototype: HTMLElsaLoginPageElement;
        new (): HTMLElsaLoginPageElement;
    };
    interface HTMLElsaModalDialogElement extends Components.ElsaModalDialog, HTMLStencilElement {
    }
    var HTMLElsaModalDialogElement: {
        prototype: HTMLElsaModalDialogElement;
        new (): HTMLElsaModalDialogElement;
    };
    interface HTMLElsaModalDialogContainerElement extends Components.ElsaModalDialogContainer, HTMLStencilElement {
    }
    var HTMLElsaModalDialogContainerElement: {
        prototype: HTMLElsaModalDialogContainerElement;
        new (): HTMLElsaModalDialogContainerElement;
    };
    interface HTMLElsaMonacoEditorElement extends Components.ElsaMonacoEditor, HTMLStencilElement {
    }
    var HTMLElsaMonacoEditorElement: {
        prototype: HTMLElsaMonacoEditorElement;
        new (): HTMLElsaMonacoEditorElement;
    };
    interface HTMLElsaMultiLineInputElement extends Components.ElsaMultiLineInput, HTMLStencilElement {
    }
    var HTMLElsaMultiLineInputElement: {
        prototype: HTMLElsaMultiLineInputElement;
        new (): HTMLElsaMultiLineInputElement;
    };
    interface HTMLElsaMultiTextInputElement extends Components.ElsaMultiTextInput, HTMLStencilElement {
    }
    var HTMLElsaMultiTextInputElement: {
        prototype: HTMLElsaMultiTextInputElement;
        new (): HTMLElsaMultiTextInputElement;
    };
    interface HTMLElsaNotificationTemplateElement extends Components.ElsaNotificationTemplate, HTMLStencilElement {
    }
    var HTMLElsaNotificationTemplateElement: {
        prototype: HTMLElsaNotificationTemplateElement;
        new (): HTMLElsaNotificationTemplateElement;
    };
    interface HTMLElsaNotificationsManagerElement extends Components.ElsaNotificationsManager, HTMLStencilElement {
    }
    var HTMLElsaNotificationsManagerElement: {
        prototype: HTMLElsaNotificationsManagerElement;
        new (): HTMLElsaNotificationsManagerElement;
    };
    interface HTMLElsaOutcomePickerInputElement extends Components.ElsaOutcomePickerInput, HTMLStencilElement {
    }
    var HTMLElsaOutcomePickerInputElement: {
        prototype: HTMLElsaOutcomePickerInputElement;
        new (): HTMLElsaOutcomePickerInputElement;
    };
    interface HTMLElsaOutputPickerInputElement extends Components.ElsaOutputPickerInput, HTMLStencilElement {
    }
    var HTMLElsaOutputPickerInputElement: {
        prototype: HTMLElsaOutputPickerInputElement;
        new (): HTMLElsaOutputPickerInputElement;
    };
    interface HTMLElsaPagerElement extends Components.ElsaPager, HTMLStencilElement {
    }
    var HTMLElsaPagerElement: {
        prototype: HTMLElsaPagerElement;
        new (): HTMLElsaPagerElement;
    };
    interface HTMLElsaPanelElement extends Components.ElsaPanel, HTMLStencilElement {
    }
    var HTMLElsaPanelElement: {
        prototype: HTMLElsaPanelElement;
        new (): HTMLElsaPanelElement;
    };
    interface HTMLElsaRadioListInputElement extends Components.ElsaRadioListInput, HTMLStencilElement {
    }
    var HTMLElsaRadioListInputElement: {
        prototype: HTMLElsaRadioListInputElement;
        new (): HTMLElsaRadioListInputElement;
    };
    interface HTMLElsaShellElement extends Components.ElsaShell, HTMLStencilElement {
    }
    var HTMLElsaShellElement: {
        prototype: HTMLElsaShellElement;
        new (): HTMLElsaShellElement;
    };
    interface HTMLElsaSingleLineInputElement extends Components.ElsaSingleLineInput, HTMLStencilElement {
    }
    var HTMLElsaSingleLineInputElement: {
        prototype: HTMLElsaSingleLineInputElement;
        new (): HTMLElsaSingleLineInputElement;
    };
    interface HTMLElsaSlideOverPanelElement extends Components.ElsaSlideOverPanel, HTMLStencilElement {
    }
    var HTMLElsaSlideOverPanelElement: {
        prototype: HTMLElsaSlideOverPanelElement;
        new (): HTMLElsaSlideOverPanelElement;
    };
    interface HTMLElsaStudioElement extends Components.ElsaStudio, HTMLStencilElement {
    }
    var HTMLElsaStudioElement: {
        prototype: HTMLElsaStudioElement;
        new (): HTMLElsaStudioElement;
    };
    interface HTMLElsaSwitchEditorElement extends Components.ElsaSwitchEditor, HTMLStencilElement {
    }
    var HTMLElsaSwitchEditorElement: {
        prototype: HTMLElsaSwitchEditorElement;
        new (): HTMLElsaSwitchEditorElement;
    };
    interface HTMLElsaToastManagerElement extends Components.ElsaToastManager, HTMLStencilElement {
    }
    var HTMLElsaToastManagerElement: {
        prototype: HTMLElsaToastManagerElement;
        new (): HTMLElsaToastManagerElement;
    };
    interface HTMLElsaToastNotificationElement extends Components.ElsaToastNotification, HTMLStencilElement {
    }
    var HTMLElsaToastNotificationElement: {
        prototype: HTMLElsaToastNotificationElement;
        new (): HTMLElsaToastNotificationElement;
    };
    interface HTMLElsaTooltipElement extends Components.ElsaTooltip, HTMLStencilElement {
    }
    var HTMLElsaTooltipElement: {
        prototype: HTMLElsaTooltipElement;
        new (): HTMLElsaTooltipElement;
    };
    interface HTMLElsaTypePickerInputElement extends Components.ElsaTypePickerInput, HTMLStencilElement {
    }
    var HTMLElsaTypePickerInputElement: {
        prototype: HTMLElsaTypePickerInputElement;
        new (): HTMLElsaTypePickerInputElement;
    };
    interface HTMLElsaVariableEditorDialogContentElement extends Components.ElsaVariableEditorDialogContent, HTMLStencilElement {
    }
    var HTMLElsaVariableEditorDialogContentElement: {
        prototype: HTMLElsaVariableEditorDialogContentElement;
        new (): HTMLElsaVariableEditorDialogContentElement;
    };
    interface HTMLElsaVariablePickerInputElement extends Components.ElsaVariablePickerInput, HTMLStencilElement {
    }
    var HTMLElsaVariablePickerInputElement: {
        prototype: HTMLElsaVariablePickerInputElement;
        new (): HTMLElsaVariablePickerInputElement;
    };
    interface HTMLElsaVariablesEditorElement extends Components.ElsaVariablesEditor, HTMLStencilElement {
    }
    var HTMLElsaVariablesEditorElement: {
        prototype: HTMLElsaVariablesEditorElement;
        new (): HTMLElsaVariablesEditorElement;
    };
    interface HTMLElsaVariablesViewerElement extends Components.ElsaVariablesViewer, HTMLStencilElement {
    }
    var HTMLElsaVariablesViewerElement: {
        prototype: HTMLElsaVariablesViewerElement;
        new (): HTMLElsaVariablesViewerElement;
    };
    interface HTMLElsaWidgetsElement extends Components.ElsaWidgets, HTMLStencilElement {
    }
    var HTMLElsaWidgetsElement: {
        prototype: HTMLElsaWidgetsElement;
        new (): HTMLElsaWidgetsElement;
    };
    interface HTMLElsaWorkflowContextProviderCheckListElement extends Components.ElsaWorkflowContextProviderCheckList, HTMLStencilElement {
    }
    var HTMLElsaWorkflowContextProviderCheckListElement: {
        prototype: HTMLElsaWorkflowContextProviderCheckListElement;
        new (): HTMLElsaWorkflowContextProviderCheckListElement;
    };
    interface HTMLElsaWorkflowContextProviderTypePickerInputElement extends Components.ElsaWorkflowContextProviderTypePickerInput, HTMLStencilElement {
    }
    var HTMLElsaWorkflowContextProviderTypePickerInputElement: {
        prototype: HTMLElsaWorkflowContextProviderTypePickerInputElement;
        new (): HTMLElsaWorkflowContextProviderTypePickerInputElement;
    };
    interface HTMLElsaWorkflowDefinitionActivityVersionSettingsElement extends Components.ElsaWorkflowDefinitionActivityVersionSettings, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionActivityVersionSettingsElement: {
        prototype: HTMLElsaWorkflowDefinitionActivityVersionSettingsElement;
        new (): HTMLElsaWorkflowDefinitionActivityVersionSettingsElement;
    };
    interface HTMLElsaWorkflowDefinitionBrowserElement extends Components.ElsaWorkflowDefinitionBrowser, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionBrowserElement: {
        prototype: HTMLElsaWorkflowDefinitionBrowserElement;
        new (): HTMLElsaWorkflowDefinitionBrowserElement;
    };
    interface HTMLElsaWorkflowDefinitionEditorElement extends Components.ElsaWorkflowDefinitionEditor, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionEditorElement: {
        prototype: HTMLElsaWorkflowDefinitionEditorElement;
        new (): HTMLElsaWorkflowDefinitionEditorElement;
    };
    interface HTMLElsaWorkflowDefinitionEditorToolbarElement extends Components.ElsaWorkflowDefinitionEditorToolbar, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionEditorToolbarElement: {
        prototype: HTMLElsaWorkflowDefinitionEditorToolbarElement;
        new (): HTMLElsaWorkflowDefinitionEditorToolbarElement;
    };
    interface HTMLElsaWorkflowDefinitionEditorToolboxElement extends Components.ElsaWorkflowDefinitionEditorToolbox, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionEditorToolboxElement: {
        prototype: HTMLElsaWorkflowDefinitionEditorToolboxElement;
        new (): HTMLElsaWorkflowDefinitionEditorToolboxElement;
    };
    interface HTMLElsaWorkflowDefinitionEditorToolboxActivitiesElement extends Components.ElsaWorkflowDefinitionEditorToolboxActivities, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionEditorToolboxActivitiesElement: {
        prototype: HTMLElsaWorkflowDefinitionEditorToolboxActivitiesElement;
        new (): HTMLElsaWorkflowDefinitionEditorToolboxActivitiesElement;
    };
    interface HTMLElsaWorkflowDefinitionInputOutputSettingsElement extends Components.ElsaWorkflowDefinitionInputOutputSettings, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionInputOutputSettingsElement: {
        prototype: HTMLElsaWorkflowDefinitionInputOutputSettingsElement;
        new (): HTMLElsaWorkflowDefinitionInputOutputSettingsElement;
    };
    interface HTMLElsaWorkflowDefinitionPickerInputElement extends Components.ElsaWorkflowDefinitionPickerInput, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionPickerInputElement: {
        prototype: HTMLElsaWorkflowDefinitionPickerInputElement;
        new (): HTMLElsaWorkflowDefinitionPickerInputElement;
    };
    interface HTMLElsaWorkflowDefinitionPropertiesEditorElement extends Components.ElsaWorkflowDefinitionPropertiesEditor, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionPropertiesEditorElement: {
        prototype: HTMLElsaWorkflowDefinitionPropertiesEditorElement;
        new (): HTMLElsaWorkflowDefinitionPropertiesEditorElement;
    };
    interface HTMLElsaWorkflowDefinitionVersionHistoryElement extends Components.ElsaWorkflowDefinitionVersionHistory, HTMLStencilElement {
    }
    var HTMLElsaWorkflowDefinitionVersionHistoryElement: {
        prototype: HTMLElsaWorkflowDefinitionVersionHistoryElement;
        new (): HTMLElsaWorkflowDefinitionVersionHistoryElement;
    };
    interface HTMLElsaWorkflowInstanceBrowserElement extends Components.ElsaWorkflowInstanceBrowser, HTMLStencilElement {
    }
    var HTMLElsaWorkflowInstanceBrowserElement: {
        prototype: HTMLElsaWorkflowInstanceBrowserElement;
        new (): HTMLElsaWorkflowInstanceBrowserElement;
    };
    interface HTMLElsaWorkflowInstancePropertiesElement extends Components.ElsaWorkflowInstanceProperties, HTMLStencilElement {
    }
    var HTMLElsaWorkflowInstancePropertiesElement: {
        prototype: HTMLElsaWorkflowInstancePropertiesElement;
        new (): HTMLElsaWorkflowInstancePropertiesElement;
    };
    interface HTMLElsaWorkflowInstanceViewerElement extends Components.ElsaWorkflowInstanceViewer, HTMLStencilElement {
    }
    var HTMLElsaWorkflowInstanceViewerElement: {
        prototype: HTMLElsaWorkflowInstanceViewerElement;
        new (): HTMLElsaWorkflowInstanceViewerElement;
    };
    interface HTMLElsaWorkflowJournalElement extends Components.ElsaWorkflowJournal, HTMLStencilElement {
    }
    var HTMLElsaWorkflowJournalElement: {
        prototype: HTMLElsaWorkflowJournalElement;
        new (): HTMLElsaWorkflowJournalElement;
    };
    interface HTMLElsaWorkflowNavigatorElement extends Components.ElsaWorkflowNavigator, HTMLStencilElement {
    }
    var HTMLElsaWorkflowNavigatorElement: {
        prototype: HTMLElsaWorkflowNavigatorElement;
        new (): HTMLElsaWorkflowNavigatorElement;
    };
    interface HTMLElsaWorkflowPublishButtonElement extends Components.ElsaWorkflowPublishButton, HTMLStencilElement {
    }
    var HTMLElsaWorkflowPublishButtonElement: {
        prototype: HTMLElsaWorkflowPublishButtonElement;
        new (): HTMLElsaWorkflowPublishButtonElement;
    };
    interface HTMLElsaWorkflowToolbarElement extends Components.ElsaWorkflowToolbar, HTMLStencilElement {
    }
    var HTMLElsaWorkflowToolbarElement: {
        prototype: HTMLElsaWorkflowToolbarElement;
        new (): HTMLElsaWorkflowToolbarElement;
    };
    interface HTMLElsaWorkflowToolbarMenuElement extends Components.ElsaWorkflowToolbarMenu, HTMLStencilElement {
    }
    var HTMLElsaWorkflowToolbarMenuElement: {
        prototype: HTMLElsaWorkflowToolbarMenuElement;
        new (): HTMLElsaWorkflowToolbarMenuElement;
    };
    interface HTMLElementTagNameMap {
        "elsa-activity-input-editor-dialog-content": HTMLElsaActivityInputEditorDialogContentElement;
        "elsa-activity-output-editor-dialog-content": HTMLElsaActivityOutputEditorDialogContentElement;
        "elsa-activity-properties": HTMLElsaActivityPropertiesElement;
        "elsa-activity-properties-editor": HTMLElsaActivityPropertiesEditorElement;
        "elsa-blank": HTMLElsaBlankElement;
        "elsa-button-group": HTMLElsaButtonGroupElement;
        "elsa-check-list": HTMLElsaCheckListElement;
        "elsa-check-list-input": HTMLElsaCheckListInputElement;
        "elsa-checkbox-input": HTMLElsaCheckboxInputElement;
        "elsa-code-editor-input": HTMLElsaCodeEditorInputElement;
        "elsa-context-menu": HTMLElsaContextMenuElement;
        "elsa-copy-button": HTMLElsaCopyButtonElement;
        "elsa-default-activity-template": HTMLElsaDefaultActivityTemplateElement;
        "elsa-dropdown-button": HTMLElsaDropdownButtonElement;
        "elsa-dropdown-input": HTMLElsaDropdownInputElement;
        "elsa-flow-switch-editor": HTMLElsaFlowSwitchEditorElement;
        "elsa-flowchart": HTMLElsaFlowchartElement;
        "elsa-form-panel": HTMLElsaFormPanelElement;
        "elsa-home-page": HTMLElsaHomePageElement;
        "elsa-http-status-codes-editor": HTMLElsaHttpStatusCodesEditorElement;
        "elsa-input-control-switch": HTMLElsaInputControlSwitchElement;
        "elsa-input-tags": HTMLElsaInputTagsElement;
        "elsa-input-tags-dropdown": HTMLElsaInputTagsDropdownElement;
        "elsa-label-picker": HTMLElsaLabelPickerElement;
        "elsa-login-page": HTMLElsaLoginPageElement;
        "elsa-modal-dialog": HTMLElsaModalDialogElement;
        "elsa-modal-dialog-container": HTMLElsaModalDialogContainerElement;
        "elsa-monaco-editor": HTMLElsaMonacoEditorElement;
        "elsa-multi-line-input": HTMLElsaMultiLineInputElement;
        "elsa-multi-text-input": HTMLElsaMultiTextInputElement;
        "elsa-notification-template": HTMLElsaNotificationTemplateElement;
        "elsa-notifications-manager": HTMLElsaNotificationsManagerElement;
        "elsa-outcome-picker-input": HTMLElsaOutcomePickerInputElement;
        "elsa-output-picker-input": HTMLElsaOutputPickerInputElement;
        "elsa-pager": HTMLElsaPagerElement;
        "elsa-panel": HTMLElsaPanelElement;
        "elsa-radio-list-input": HTMLElsaRadioListInputElement;
        "elsa-shell": HTMLElsaShellElement;
        "elsa-single-line-input": HTMLElsaSingleLineInputElement;
        "elsa-slide-over-panel": HTMLElsaSlideOverPanelElement;
        "elsa-studio": HTMLElsaStudioElement;
        "elsa-switch-editor": HTMLElsaSwitchEditorElement;
        "elsa-toast-manager": HTMLElsaToastManagerElement;
        "elsa-toast-notification": HTMLElsaToastNotificationElement;
        "elsa-tooltip": HTMLElsaTooltipElement;
        "elsa-type-picker-input": HTMLElsaTypePickerInputElement;
        "elsa-variable-editor-dialog-content": HTMLElsaVariableEditorDialogContentElement;
        "elsa-variable-picker-input": HTMLElsaVariablePickerInputElement;
        "elsa-variables-editor": HTMLElsaVariablesEditorElement;
        "elsa-variables-viewer": HTMLElsaVariablesViewerElement;
        "elsa-widgets": HTMLElsaWidgetsElement;
        "elsa-workflow-context-provider-check-list": HTMLElsaWorkflowContextProviderCheckListElement;
        "elsa-workflow-context-provider-type-picker-input": HTMLElsaWorkflowContextProviderTypePickerInputElement;
        "elsa-workflow-definition-activity-version-settings": HTMLElsaWorkflowDefinitionActivityVersionSettingsElement;
        "elsa-workflow-definition-browser": HTMLElsaWorkflowDefinitionBrowserElement;
        "elsa-workflow-definition-editor": HTMLElsaWorkflowDefinitionEditorElement;
        "elsa-workflow-definition-editor-toolbar": HTMLElsaWorkflowDefinitionEditorToolbarElement;
        "elsa-workflow-definition-editor-toolbox": HTMLElsaWorkflowDefinitionEditorToolboxElement;
        "elsa-workflow-definition-editor-toolbox-activities": HTMLElsaWorkflowDefinitionEditorToolboxActivitiesElement;
        "elsa-workflow-definition-input-output-settings": HTMLElsaWorkflowDefinitionInputOutputSettingsElement;
        "elsa-workflow-definition-picker-input": HTMLElsaWorkflowDefinitionPickerInputElement;
        "elsa-workflow-definition-properties-editor": HTMLElsaWorkflowDefinitionPropertiesEditorElement;
        "elsa-workflow-definition-version-history": HTMLElsaWorkflowDefinitionVersionHistoryElement;
        "elsa-workflow-instance-browser": HTMLElsaWorkflowInstanceBrowserElement;
        "elsa-workflow-instance-properties": HTMLElsaWorkflowInstancePropertiesElement;
        "elsa-workflow-instance-viewer": HTMLElsaWorkflowInstanceViewerElement;
        "elsa-workflow-journal": HTMLElsaWorkflowJournalElement;
        "elsa-workflow-navigator": HTMLElsaWorkflowNavigatorElement;
        "elsa-workflow-publish-button": HTMLElsaWorkflowPublishButtonElement;
        "elsa-workflow-toolbar": HTMLElsaWorkflowToolbarElement;
        "elsa-workflow-toolbar-menu": HTMLElsaWorkflowToolbarMenuElement;
    }
}
declare namespace LocalJSX {
    interface ElsaActivityInputEditorDialogContent {
        "input"?: InputDefinition;
        "onInputChanged"?: (event: ElsaActivityInputEditorDialogContentCustomEvent<InputDefinition>) => void;
    }
    interface ElsaActivityOutputEditorDialogContent {
        "onOutputChanged"?: (event: ElsaActivityOutputEditorDialogContentCustomEvent<OutputDefinition>) => void;
        "output"?: OutputDefinition;
    }
    interface ElsaActivityProperties {
        "activity"?: Activity;
        "activityExecutionLog"?: WorkflowExecutionLogRecord;
        "activityPropertyTabIndex"?: number;
    }
    interface ElsaActivityPropertiesEditor {
        "activity"?: Activity;
        "onActivityUpdated"?: (event: ElsaActivityPropertiesEditorCustomEvent<ActivityUpdatedArgs>) => void;
        "onDeleteActivityRequested"?: (event: ElsaActivityPropertiesEditorCustomEvent<DeleteActivityRequestedArgs>) => void;
        "outputs"?: Array<OutputDefinition>;
        "variables"?: Array<Variable>;
        "workflowDefinitionId"?: string;
    }
    interface ElsaBlank {
    }
    interface ElsaButtonGroup {
        "buttons"?: Array<Button>;
    }
    interface ElsaCheckList {
        "fieldName"?: string;
        "onSelectedValuesChanged"?: (event: ElsaCheckListCustomEvent<Array<string> | number>) => void;
        "selectList"?: SelectList;
        "selectedValue"?: number;
        "selectedValues"?: Array<string>;
    }
    interface ElsaCheckListInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaCheckboxInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaCodeEditorInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaContextMenu {
        "anchorPoint"?: ContextMenuAnchorPoint;
        "hideButton"?: boolean;
        "menuItems"?: Array<ContextMenuItem>;
    }
    interface ElsaCopyButton {
        "value"?: string;
    }
    interface ElsaDefaultActivityTemplate {
        "activityId"?: string;
        "activityType"?: string;
        "activityTypeVersion"?: number;
        "displayType"?: string;
        "onChildActivitySelected"?: (event: ElsaDefaultActivityTemplateCustomEvent<ChildActivitySelectedArgs>) => void;
        "onEditChildActivity"?: (event: ElsaDefaultActivityTemplateCustomEvent<EditChildActivityArgs>) => void;
    }
    interface ElsaDropdownButton {
        "handler"?: () => void;
        "icon"?: any;
        "items"?: Array<DropdownButtonItem>;
        "onItemSelected"?: (event: ElsaDropdownButtonCustomEvent<DropdownButtonItem>) => void;
        "onMenuOpened"?: (event: ElsaDropdownButtonCustomEvent<void>) => void;
        "origin"?: DropdownButtonOrigin;
        "text"?: string;
        "theme"?: ('Primary' | 'Secondary');
    }
    interface ElsaDropdownInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaFlowSwitchEditor {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaFlowchart {
        "interactiveMode"?: boolean;
        "onActivityDeleted"?: (event: ElsaFlowchartCustomEvent<ActivityDeletedArgs>) => void;
        "onActivitySelected"?: (event: ElsaFlowchartCustomEvent<ActivitySelectedArgs>) => void;
        "onChildActivitySelected"?: (event: ElsaFlowchartCustomEvent<ChildActivitySelectedArgs>) => void;
        "onContainerSelected"?: (event: ElsaFlowchartCustomEvent<ContainerSelectedArgs>) => void;
        "onGraphUpdated"?: (event: ElsaFlowchartCustomEvent<GraphUpdatedArgs>) => void;
        "onWorkflowUpdated"?: (event: ElsaFlowchartCustomEvent<WorkflowUpdatedArgs>) => void;
        "rootActivity"?: Activity;
        "silent"?: boolean;
    }
    interface ElsaFormPanel {
        "actions"?: Array<PanelActionDefinition>;
        "mainTitle"?: string;
        "onActionInvoked"?: (event: ElsaFormPanelCustomEvent<PanelActionClickArgs>) => void;
        "onSelectedTabIndexChanged"?: (event: ElsaFormPanelCustomEvent<TabChangedArgs>) => void;
        "onSubmitted"?: (event: ElsaFormPanelCustomEvent<FormData>) => void;
        "orientation"?: 'Landscape' | 'Portrait';
        "selectedTabIndex"?: number;
        "subTitle"?: string;
        "tabs"?: Array<TabDefinition>;
    }
    interface ElsaHomePage {
    }
    interface ElsaHttpStatusCodesEditor {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaInputControlSwitch {
        "activityType"?: string;
        "codeEditorHeight"?: string;
        "codeEditorSingleLineMode"?: boolean;
        "context"?: IntellisenseContext;
        "defaultSyntax"?: string;
        "expression"?: string;
        "fieldName"?: string;
        "hideLabel"?: boolean;
        "hint"?: string;
        "isReadOnly"?: boolean;
        "label"?: string;
        "onExpressionChanged"?: (event: ElsaInputControlSwitchCustomEvent<ExpressionChangedArs>) => void;
        "onSyntaxChanged"?: (event: ElsaInputControlSwitchCustomEvent<string>) => void;
        "propertyName"?: string;
        "supportedSyntaxes"?: Array<string>;
        "syntax"?: string;
        "workflowDefinitionId"?: string;
    }
    interface ElsaInputTags {
        "fieldId"?: string;
        "onValueChanged"?: (event: ElsaInputTagsCustomEvent<Array<string>>) => void;
        "placeHolder"?: string;
        "values"?: Array<string>;
    }
    interface ElsaInputTagsDropdown {
        "dropdownValues"?: Array<SelectListItem>;
        "fieldId"?: string;
        "fieldName"?: string;
        "onValueChanged"?: (event: ElsaInputTagsDropdownCustomEvent<SelectListItem[]| string[]>) => void;
        "placeHolder"?: string;
        "values"?: Array<string | SelectListItem>;
    }
    interface ElsaLabelPicker {
        "buttonClass"?: string;
        "containerClass"?: string;
        "onSelectedLabelsChanged"?: (event: ElsaLabelPickerCustomEvent<Array<string>>) => void;
        "selectedLabels"?: Array<string>;
    }
    interface ElsaLoginPage {
        "onSignedIn"?: (event: ElsaLoginPageCustomEvent<SignedInArgs>) => void;
    }
    interface ElsaModalDialog {
        "actions"?: Array<ModalActionDefinition>;
        "autoHide"?: boolean;
        "content"?: () => any;
        "modalDialogInstance"?: ModalDialogInstance;
        "onActionInvoked"?: (event: ElsaModalDialogCustomEvent<ModalActionClickArgs>) => void;
        "onHidden"?: (event: ElsaModalDialogCustomEvent<any>) => void;
        "onShown"?: (event: ElsaModalDialogCustomEvent<any>) => void;
        "size"?: string;
        "type"?: ModalType;
    }
    interface ElsaModalDialogContainer {
    }
    interface ElsaMonacoEditor {
        "editorHeight"?: string;
        "language"?: string;
        "onValueChanged"?: (event: ElsaMonacoEditorCustomEvent<MonacoValueChangedArgs>) => void;
        "padding"?: string;
        "singleLineMode"?: boolean;
        "value"?: string;
    }
    interface ElsaMultiLineInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaMultiTextInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaNotificationTemplate {
        "notification"?: NotificationType;
    }
    interface ElsaNotificationsManager {
        "modalState"?: boolean;
    }
    interface ElsaOutcomePickerInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaOutputPickerInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaPager {
        "onPaginated"?: (event: ElsaPagerCustomEvent<PagerData>) => void;
        "page"?: number;
        "pageSize"?: number;
        "totalCount"?: number;
    }
    interface ElsaPanel {
        "onExpandedStateChanged"?: (event: ElsaPanelCustomEvent<PanelStateChangedArgs>) => void;
        "position"?: PanelPosition;
    }
    interface ElsaRadioListInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaShell {
        "onInitializing"?: (event: ElsaShellCustomEvent<ShellInitializingContext>) => void;
    }
    interface ElsaSingleLineInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaSlideOverPanel {
        "actions"?: Array<PanelActionDefinition>;
        "expand"?: boolean;
        "headerText"?: string;
        "onCollapsed"?: (event: ElsaSlideOverPanelCustomEvent<any>) => void;
        "selectedTab"?: TabDefinition;
        "tabs"?: Array<TabDefinition>;
    }
    interface ElsaStudio {
        "enableFlexiblePorts"?: boolean;
        "monacoLibPath"?: string;
        "serverUrl"?: string;
    }
    interface ElsaSwitchEditor {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaToastManager {
    }
    interface ElsaToastNotification {
        "notification"?: NotificationType;
        "showDuration"?: number;
    }
    interface ElsaTooltip {
        "tooltipContent"?: any;
        /**
          * Specifying `auto` will default to `bottom`, but will reposition to `top` if the tooltip height runs offscreen
         */
        "tooltipPosition"?: 'right' | 'left' | 'top' | 'bottom' | 'auto';
    }
    interface ElsaTypePickerInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaVariableEditorDialogContent {
        "onVariableChanged"?: (event: ElsaVariableEditorDialogContentCustomEvent<Variable>) => void;
        "variable"?: Variable;
    }
    interface ElsaVariablePickerInput {
        "inputContext"?: ActivityInputContext;
        "workflowDefinition"?: WorkflowDefinition;
    }
    interface ElsaVariablesEditor {
        "onVariablesChanged"?: (event: ElsaVariablesEditorCustomEvent<Variable[]>) => void;
        "variables"?: Array<Variable>;
    }
    interface ElsaVariablesViewer {
        "variables"?: Array<Variable>;
        "workflowDefinition"?: WorkflowDefinition;
        "workflowInstance"?: WorkflowInstance;
    }
    interface ElsaWidgets {
        "widgets"?: Array<Widget>;
    }
    interface ElsaWorkflowContextProviderCheckList {
        "descriptors"?: Array<WorkflowContextProviderDescriptor>;
        "onWorkflowDefinitionChanged"?: (event: ElsaWorkflowContextProviderCheckListCustomEvent<WorkflowDefinition>) => void;
        "workflowDefinition"?: WorkflowDefinition;
    }
    interface ElsaWorkflowContextProviderTypePickerInput {
        "descriptors"?: Array<WorkflowContextProviderDescriptor>;
        "inputContext"?: ActivityInputContext;
        "workflowDefinition"?: WorkflowDefinition;
    }
    interface ElsaWorkflowDefinitionActivityVersionSettings {
        "renderContext"?: RenderActivityPropsContext;
    }
    interface ElsaWorkflowDefinitionBrowser {
        "onNewWorkflowDefinitionSelected"?: (event: ElsaWorkflowDefinitionBrowserCustomEvent<any>) => void;
        "onWorkflowDefinitionSelected"?: (event: ElsaWorkflowDefinitionBrowserCustomEvent<WorkflowDefinitionSummary>) => void;
    }
    interface ElsaWorkflowDefinitionEditor {
        "monacoLibPath"?: string;
        "onWorkflowUpdated"?: (event: ElsaWorkflowDefinitionEditorCustomEvent<WorkflowDefinitionUpdatedArgs>) => void;
        "workflowDefinition"?: WorkflowDefinition;
    }
    interface ElsaWorkflowDefinitionEditorToolbar {
        "onAutoLayout"?: (event: ElsaWorkflowDefinitionEditorToolbarCustomEvent<LayoutDirection>) => void;
        "zoomToFit"?: () => Promise<void>;
    }
    interface ElsaWorkflowDefinitionEditorToolbox {
        "graph"?: Graph;
    }
    interface ElsaWorkflowDefinitionEditorToolboxActivities {
        "graph"?: Graph;
    }
    interface ElsaWorkflowDefinitionInputOutputSettings {
        "inputs"?: Array<InputDefinition>;
        "onInputsChanged"?: (event: ElsaWorkflowDefinitionInputOutputSettingsCustomEvent<InputDefinition[]>) => void;
        "onOutcomesChanged"?: (event: ElsaWorkflowDefinitionInputOutputSettingsCustomEvent<Array<string>>) => void;
        "onOutputsChanged"?: (event: ElsaWorkflowDefinitionInputOutputSettingsCustomEvent<OutputDefinition[]>) => void;
        "outcomes"?: Array<string>;
        "outputs"?: Array<OutputDefinition>;
    }
    interface ElsaWorkflowDefinitionPickerInput {
        "inputContext"?: ActivityInputContext;
    }
    interface ElsaWorkflowDefinitionPropertiesEditor {
        "onDeleteVersionClicked"?: (event: ElsaWorkflowDefinitionPropertiesEditorCustomEvent<WorkflowDefinition>) => void;
        "onRevertVersionClicked"?: (event: ElsaWorkflowDefinitionPropertiesEditorCustomEvent<WorkflowDefinition>) => void;
        "onVersionSelected"?: (event: ElsaWorkflowDefinitionPropertiesEditorCustomEvent<WorkflowDefinition>) => void;
        "onWorkflowPropsUpdated"?: (event: ElsaWorkflowDefinitionPropertiesEditorCustomEvent<WorkflowDefinitionPropsUpdatedArgs>) => void;
        "workflowDefinition"?: WorkflowDefinition;
        "workflowVersions"?: Array<WorkflowDefinition>;
    }
    interface ElsaWorkflowDefinitionVersionHistory {
        "onDeleteVersionClicked"?: (event: ElsaWorkflowDefinitionVersionHistoryCustomEvent<WorkflowDefinition>) => void;
        "onRevertVersionClicked"?: (event: ElsaWorkflowDefinitionVersionHistoryCustomEvent<WorkflowDefinition>) => void;
        "onVersionSelected"?: (event: ElsaWorkflowDefinitionVersionHistoryCustomEvent<WorkflowDefinition>) => void;
        "selectedVersion"?: WorkflowDefinition;
        "serverUrl"?: string;
        "workflowVersions"?: Array<WorkflowDefinition>;
    }
    interface ElsaWorkflowInstanceBrowser {
        "onWorkflowInstanceSelected"?: (event: ElsaWorkflowInstanceBrowserCustomEvent<WorkflowInstanceSummary>) => void;
    }
    interface ElsaWorkflowInstanceProperties {
        "workflowDefinition"?: WorkflowDefinition;
        "workflowInstance"?: WorkflowInstance;
    }
    interface ElsaWorkflowInstanceViewer {
        "monacoLibPath"?: string;
        "workflowDefinition"?: WorkflowDefinition;
        "workflowInstance"?: WorkflowInstance;
    }
    interface ElsaWorkflowJournal {
        "onJournalItemSelected"?: (event: ElsaWorkflowJournalCustomEvent<JournalItemSelectedArgs>) => void;
        "workflowDefinition"?: WorkflowDefinition;
        "workflowInstance"?: WorkflowInstance;
    }
    interface ElsaWorkflowNavigator {
        "items"?: Array<FlowchartPathItem>;
        "onNavigate"?: (event: ElsaWorkflowNavigatorCustomEvent<FlowchartPathItem>) => void;
        "rootActivity"?: Activity;
    }
    interface ElsaWorkflowPublishButton {
        "onExportClicked"?: (event: ElsaWorkflowPublishButtonCustomEvent<any>) => void;
        "onImportClicked"?: (event: ElsaWorkflowPublishButtonCustomEvent<File>) => void;
        "onNewClicked"?: (event: ElsaWorkflowPublishButtonCustomEvent<any>) => void;
        "onPublishClicked"?: (event: ElsaWorkflowPublishButtonCustomEvent<PublishClickedArgs>) => void;
        "onUnPublishClicked"?: (event: ElsaWorkflowPublishButtonCustomEvent<any>) => void;
        "publishing"?: boolean;
    }
    interface ElsaWorkflowToolbar {
    }
    interface ElsaWorkflowToolbarMenu {
    }
    interface IntrinsicElements {
        "elsa-activity-input-editor-dialog-content": ElsaActivityInputEditorDialogContent;
        "elsa-activity-output-editor-dialog-content": ElsaActivityOutputEditorDialogContent;
        "elsa-activity-properties": ElsaActivityProperties;
        "elsa-activity-properties-editor": ElsaActivityPropertiesEditor;
        "elsa-blank": ElsaBlank;
        "elsa-button-group": ElsaButtonGroup;
        "elsa-check-list": ElsaCheckList;
        "elsa-check-list-input": ElsaCheckListInput;
        "elsa-checkbox-input": ElsaCheckboxInput;
        "elsa-code-editor-input": ElsaCodeEditorInput;
        "elsa-context-menu": ElsaContextMenu;
        "elsa-copy-button": ElsaCopyButton;
        "elsa-default-activity-template": ElsaDefaultActivityTemplate;
        "elsa-dropdown-button": ElsaDropdownButton;
        "elsa-dropdown-input": ElsaDropdownInput;
        "elsa-flow-switch-editor": ElsaFlowSwitchEditor;
        "elsa-flowchart": ElsaFlowchart;
        "elsa-form-panel": ElsaFormPanel;
        "elsa-home-page": ElsaHomePage;
        "elsa-http-status-codes-editor": ElsaHttpStatusCodesEditor;
        "elsa-input-control-switch": ElsaInputControlSwitch;
        "elsa-input-tags": ElsaInputTags;
        "elsa-input-tags-dropdown": ElsaInputTagsDropdown;
        "elsa-label-picker": ElsaLabelPicker;
        "elsa-login-page": ElsaLoginPage;
        "elsa-modal-dialog": ElsaModalDialog;
        "elsa-modal-dialog-container": ElsaModalDialogContainer;
        "elsa-monaco-editor": ElsaMonacoEditor;
        "elsa-multi-line-input": ElsaMultiLineInput;
        "elsa-multi-text-input": ElsaMultiTextInput;
        "elsa-notification-template": ElsaNotificationTemplate;
        "elsa-notifications-manager": ElsaNotificationsManager;
        "elsa-outcome-picker-input": ElsaOutcomePickerInput;
        "elsa-output-picker-input": ElsaOutputPickerInput;
        "elsa-pager": ElsaPager;
        "elsa-panel": ElsaPanel;
        "elsa-radio-list-input": ElsaRadioListInput;
        "elsa-shell": ElsaShell;
        "elsa-single-line-input": ElsaSingleLineInput;
        "elsa-slide-over-panel": ElsaSlideOverPanel;
        "elsa-studio": ElsaStudio;
        "elsa-switch-editor": ElsaSwitchEditor;
        "elsa-toast-manager": ElsaToastManager;
        "elsa-toast-notification": ElsaToastNotification;
        "elsa-tooltip": ElsaTooltip;
        "elsa-type-picker-input": ElsaTypePickerInput;
        "elsa-variable-editor-dialog-content": ElsaVariableEditorDialogContent;
        "elsa-variable-picker-input": ElsaVariablePickerInput;
        "elsa-variables-editor": ElsaVariablesEditor;
        "elsa-variables-viewer": ElsaVariablesViewer;
        "elsa-widgets": ElsaWidgets;
        "elsa-workflow-context-provider-check-list": ElsaWorkflowContextProviderCheckList;
        "elsa-workflow-context-provider-type-picker-input": ElsaWorkflowContextProviderTypePickerInput;
        "elsa-workflow-definition-activity-version-settings": ElsaWorkflowDefinitionActivityVersionSettings;
        "elsa-workflow-definition-browser": ElsaWorkflowDefinitionBrowser;
        "elsa-workflow-definition-editor": ElsaWorkflowDefinitionEditor;
        "elsa-workflow-definition-editor-toolbar": ElsaWorkflowDefinitionEditorToolbar;
        "elsa-workflow-definition-editor-toolbox": ElsaWorkflowDefinitionEditorToolbox;
        "elsa-workflow-definition-editor-toolbox-activities": ElsaWorkflowDefinitionEditorToolboxActivities;
        "elsa-workflow-definition-input-output-settings": ElsaWorkflowDefinitionInputOutputSettings;
        "elsa-workflow-definition-picker-input": ElsaWorkflowDefinitionPickerInput;
        "elsa-workflow-definition-properties-editor": ElsaWorkflowDefinitionPropertiesEditor;
        "elsa-workflow-definition-version-history": ElsaWorkflowDefinitionVersionHistory;
        "elsa-workflow-instance-browser": ElsaWorkflowInstanceBrowser;
        "elsa-workflow-instance-properties": ElsaWorkflowInstanceProperties;
        "elsa-workflow-instance-viewer": ElsaWorkflowInstanceViewer;
        "elsa-workflow-journal": ElsaWorkflowJournal;
        "elsa-workflow-navigator": ElsaWorkflowNavigator;
        "elsa-workflow-publish-button": ElsaWorkflowPublishButton;
        "elsa-workflow-toolbar": ElsaWorkflowToolbar;
        "elsa-workflow-toolbar-menu": ElsaWorkflowToolbarMenu;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "elsa-activity-input-editor-dialog-content": LocalJSX.ElsaActivityInputEditorDialogContent & JSXBase.HTMLAttributes<HTMLElsaActivityInputEditorDialogContentElement>;
            "elsa-activity-output-editor-dialog-content": LocalJSX.ElsaActivityOutputEditorDialogContent & JSXBase.HTMLAttributes<HTMLElsaActivityOutputEditorDialogContentElement>;
            "elsa-activity-properties": LocalJSX.ElsaActivityProperties & JSXBase.HTMLAttributes<HTMLElsaActivityPropertiesElement>;
            "elsa-activity-properties-editor": LocalJSX.ElsaActivityPropertiesEditor & JSXBase.HTMLAttributes<HTMLElsaActivityPropertiesEditorElement>;
            "elsa-blank": LocalJSX.ElsaBlank & JSXBase.HTMLAttributes<HTMLElsaBlankElement>;
            "elsa-button-group": LocalJSX.ElsaButtonGroup & JSXBase.HTMLAttributes<HTMLElsaButtonGroupElement>;
            "elsa-check-list": LocalJSX.ElsaCheckList & JSXBase.HTMLAttributes<HTMLElsaCheckListElement>;
            "elsa-check-list-input": LocalJSX.ElsaCheckListInput & JSXBase.HTMLAttributes<HTMLElsaCheckListInputElement>;
            "elsa-checkbox-input": LocalJSX.ElsaCheckboxInput & JSXBase.HTMLAttributes<HTMLElsaCheckboxInputElement>;
            "elsa-code-editor-input": LocalJSX.ElsaCodeEditorInput & JSXBase.HTMLAttributes<HTMLElsaCodeEditorInputElement>;
            "elsa-context-menu": LocalJSX.ElsaContextMenu & JSXBase.HTMLAttributes<HTMLElsaContextMenuElement>;
            "elsa-copy-button": LocalJSX.ElsaCopyButton & JSXBase.HTMLAttributes<HTMLElsaCopyButtonElement>;
            "elsa-default-activity-template": LocalJSX.ElsaDefaultActivityTemplate & JSXBase.HTMLAttributes<HTMLElsaDefaultActivityTemplateElement>;
            "elsa-dropdown-button": LocalJSX.ElsaDropdownButton & JSXBase.HTMLAttributes<HTMLElsaDropdownButtonElement>;
            "elsa-dropdown-input": LocalJSX.ElsaDropdownInput & JSXBase.HTMLAttributes<HTMLElsaDropdownInputElement>;
            "elsa-flow-switch-editor": LocalJSX.ElsaFlowSwitchEditor & JSXBase.HTMLAttributes<HTMLElsaFlowSwitchEditorElement>;
            "elsa-flowchart": LocalJSX.ElsaFlowchart & JSXBase.HTMLAttributes<HTMLElsaFlowchartElement>;
            "elsa-form-panel": LocalJSX.ElsaFormPanel & JSXBase.HTMLAttributes<HTMLElsaFormPanelElement>;
            "elsa-home-page": LocalJSX.ElsaHomePage & JSXBase.HTMLAttributes<HTMLElsaHomePageElement>;
            "elsa-http-status-codes-editor": LocalJSX.ElsaHttpStatusCodesEditor & JSXBase.HTMLAttributes<HTMLElsaHttpStatusCodesEditorElement>;
            "elsa-input-control-switch": LocalJSX.ElsaInputControlSwitch & JSXBase.HTMLAttributes<HTMLElsaInputControlSwitchElement>;
            "elsa-input-tags": LocalJSX.ElsaInputTags & JSXBase.HTMLAttributes<HTMLElsaInputTagsElement>;
            "elsa-input-tags-dropdown": LocalJSX.ElsaInputTagsDropdown & JSXBase.HTMLAttributes<HTMLElsaInputTagsDropdownElement>;
            "elsa-label-picker": LocalJSX.ElsaLabelPicker & JSXBase.HTMLAttributes<HTMLElsaLabelPickerElement>;
            "elsa-login-page": LocalJSX.ElsaLoginPage & JSXBase.HTMLAttributes<HTMLElsaLoginPageElement>;
            "elsa-modal-dialog": LocalJSX.ElsaModalDialog & JSXBase.HTMLAttributes<HTMLElsaModalDialogElement>;
            "elsa-modal-dialog-container": LocalJSX.ElsaModalDialogContainer & JSXBase.HTMLAttributes<HTMLElsaModalDialogContainerElement>;
            "elsa-monaco-editor": LocalJSX.ElsaMonacoEditor & JSXBase.HTMLAttributes<HTMLElsaMonacoEditorElement>;
            "elsa-multi-line-input": LocalJSX.ElsaMultiLineInput & JSXBase.HTMLAttributes<HTMLElsaMultiLineInputElement>;
            "elsa-multi-text-input": LocalJSX.ElsaMultiTextInput & JSXBase.HTMLAttributes<HTMLElsaMultiTextInputElement>;
            "elsa-notification-template": LocalJSX.ElsaNotificationTemplate & JSXBase.HTMLAttributes<HTMLElsaNotificationTemplateElement>;
            "elsa-notifications-manager": LocalJSX.ElsaNotificationsManager & JSXBase.HTMLAttributes<HTMLElsaNotificationsManagerElement>;
            "elsa-outcome-picker-input": LocalJSX.ElsaOutcomePickerInput & JSXBase.HTMLAttributes<HTMLElsaOutcomePickerInputElement>;
            "elsa-output-picker-input": LocalJSX.ElsaOutputPickerInput & JSXBase.HTMLAttributes<HTMLElsaOutputPickerInputElement>;
            "elsa-pager": LocalJSX.ElsaPager & JSXBase.HTMLAttributes<HTMLElsaPagerElement>;
            "elsa-panel": LocalJSX.ElsaPanel & JSXBase.HTMLAttributes<HTMLElsaPanelElement>;
            "elsa-radio-list-input": LocalJSX.ElsaRadioListInput & JSXBase.HTMLAttributes<HTMLElsaRadioListInputElement>;
            "elsa-shell": LocalJSX.ElsaShell & JSXBase.HTMLAttributes<HTMLElsaShellElement>;
            "elsa-single-line-input": LocalJSX.ElsaSingleLineInput & JSXBase.HTMLAttributes<HTMLElsaSingleLineInputElement>;
            "elsa-slide-over-panel": LocalJSX.ElsaSlideOverPanel & JSXBase.HTMLAttributes<HTMLElsaSlideOverPanelElement>;
            "elsa-studio": LocalJSX.ElsaStudio & JSXBase.HTMLAttributes<HTMLElsaStudioElement>;
            "elsa-switch-editor": LocalJSX.ElsaSwitchEditor & JSXBase.HTMLAttributes<HTMLElsaSwitchEditorElement>;
            "elsa-toast-manager": LocalJSX.ElsaToastManager & JSXBase.HTMLAttributes<HTMLElsaToastManagerElement>;
            "elsa-toast-notification": LocalJSX.ElsaToastNotification & JSXBase.HTMLAttributes<HTMLElsaToastNotificationElement>;
            "elsa-tooltip": LocalJSX.ElsaTooltip & JSXBase.HTMLAttributes<HTMLElsaTooltipElement>;
            "elsa-type-picker-input": LocalJSX.ElsaTypePickerInput & JSXBase.HTMLAttributes<HTMLElsaTypePickerInputElement>;
            "elsa-variable-editor-dialog-content": LocalJSX.ElsaVariableEditorDialogContent & JSXBase.HTMLAttributes<HTMLElsaVariableEditorDialogContentElement>;
            "elsa-variable-picker-input": LocalJSX.ElsaVariablePickerInput & JSXBase.HTMLAttributes<HTMLElsaVariablePickerInputElement>;
            "elsa-variables-editor": LocalJSX.ElsaVariablesEditor & JSXBase.HTMLAttributes<HTMLElsaVariablesEditorElement>;
            "elsa-variables-viewer": LocalJSX.ElsaVariablesViewer & JSXBase.HTMLAttributes<HTMLElsaVariablesViewerElement>;
            "elsa-widgets": LocalJSX.ElsaWidgets & JSXBase.HTMLAttributes<HTMLElsaWidgetsElement>;
            "elsa-workflow-context-provider-check-list": LocalJSX.ElsaWorkflowContextProviderCheckList & JSXBase.HTMLAttributes<HTMLElsaWorkflowContextProviderCheckListElement>;
            "elsa-workflow-context-provider-type-picker-input": LocalJSX.ElsaWorkflowContextProviderTypePickerInput & JSXBase.HTMLAttributes<HTMLElsaWorkflowContextProviderTypePickerInputElement>;
            "elsa-workflow-definition-activity-version-settings": LocalJSX.ElsaWorkflowDefinitionActivityVersionSettings & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionActivityVersionSettingsElement>;
            "elsa-workflow-definition-browser": LocalJSX.ElsaWorkflowDefinitionBrowser & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionBrowserElement>;
            "elsa-workflow-definition-editor": LocalJSX.ElsaWorkflowDefinitionEditor & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionEditorElement>;
            "elsa-workflow-definition-editor-toolbar": LocalJSX.ElsaWorkflowDefinitionEditorToolbar & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionEditorToolbarElement>;
            "elsa-workflow-definition-editor-toolbox": LocalJSX.ElsaWorkflowDefinitionEditorToolbox & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionEditorToolboxElement>;
            "elsa-workflow-definition-editor-toolbox-activities": LocalJSX.ElsaWorkflowDefinitionEditorToolboxActivities & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionEditorToolboxActivitiesElement>;
            "elsa-workflow-definition-input-output-settings": LocalJSX.ElsaWorkflowDefinitionInputOutputSettings & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionInputOutputSettingsElement>;
            "elsa-workflow-definition-picker-input": LocalJSX.ElsaWorkflowDefinitionPickerInput & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionPickerInputElement>;
            "elsa-workflow-definition-properties-editor": LocalJSX.ElsaWorkflowDefinitionPropertiesEditor & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionPropertiesEditorElement>;
            "elsa-workflow-definition-version-history": LocalJSX.ElsaWorkflowDefinitionVersionHistory & JSXBase.HTMLAttributes<HTMLElsaWorkflowDefinitionVersionHistoryElement>;
            "elsa-workflow-instance-browser": LocalJSX.ElsaWorkflowInstanceBrowser & JSXBase.HTMLAttributes<HTMLElsaWorkflowInstanceBrowserElement>;
            "elsa-workflow-instance-properties": LocalJSX.ElsaWorkflowInstanceProperties & JSXBase.HTMLAttributes<HTMLElsaWorkflowInstancePropertiesElement>;
            "elsa-workflow-instance-viewer": LocalJSX.ElsaWorkflowInstanceViewer & JSXBase.HTMLAttributes<HTMLElsaWorkflowInstanceViewerElement>;
            "elsa-workflow-journal": LocalJSX.ElsaWorkflowJournal & JSXBase.HTMLAttributes<HTMLElsaWorkflowJournalElement>;
            "elsa-workflow-navigator": LocalJSX.ElsaWorkflowNavigator & JSXBase.HTMLAttributes<HTMLElsaWorkflowNavigatorElement>;
            "elsa-workflow-publish-button": LocalJSX.ElsaWorkflowPublishButton & JSXBase.HTMLAttributes<HTMLElsaWorkflowPublishButtonElement>;
            "elsa-workflow-toolbar": LocalJSX.ElsaWorkflowToolbar & JSXBase.HTMLAttributes<HTMLElsaWorkflowToolbarElement>;
            "elsa-workflow-toolbar-menu": LocalJSX.ElsaWorkflowToolbarMenu & JSXBase.HTMLAttributes<HTMLElsaWorkflowToolbarMenuElement>;
        }
    }
}
