<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" />
        <PackageReference Include="TUnit.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\src\apps\Elsa.Server.Web\Elsa.Server.Web.csproj" />
        <ProjectReference Include="..\..\..\src\apps\Elsa.ModularServer.Web\Elsa.ModularServer.Web.csproj" />
        <ProjectReference Include="..\..\..\src\common\Elsa.Testing.Shared\Elsa.Testing.Shared.csproj" />
    </ItemGroup>

</Project>
