<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <IsPackable>false</IsPackable>
        <!-- Pomelo.EntityFrameworkCore.MySql 9.0.0 doesn't support EF Core 10; no Pomelo 10.x exists yet -->
        <NoWarn>$(NoWarn);NU1608</NoWarn>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Elsa" />
        <PackageReference Include="Elsa.Common" />
		<PackageReference Include="Elsa.Expressions.CSharp" />
		<PackageReference Include="Elsa.Expressions.JavaScript" />
		<PackageReference Include="Elsa.Expressions.Liquid" />
		<PackageReference Include="Elsa.Expressions.Python" />
		<PackageReference Include="Elsa.Http" />
		<PackageReference Include="Elsa.Http.Webhooks" />
        <PackageReference Include="Elsa.Persistence.EFCore.Common" />
        <PackageReference Include="Elsa.Persistence.EFCore.MySql" />
        <PackageReference Include="Elsa.Persistence.EFCore.Oracle" />
        <PackageReference Include="Elsa.Persistence.EFCore.PostgreSql" />
        <PackageReference Include="Elsa.Persistence.EFCore.Sqlite" />
        <PackageReference Include="Elsa.Persistence.EFCore.SqlServer" />
        <PackageReference Include="Elsa.Persistence.EFCore" />
        <PackageReference Include="Elsa.Tenants" />
        <PackageReference Include="Elsa.Tenants.AspNetCore" />
		<PackageReference Include="Elsa.Workflows.Api" />
        <PackageReference Include="Elsa.WorkflowProviders.BlobStorage" />
		<PackageReference Include="Elsa.Workflows.Runtime.Distributed" />
        <PackageReference Include="FluentMigrator.Runner.SqlServer" />
        <PackageReference Include="FluentMigrator.Runner.SQLite" />
        <PackageReference Include="Hangfire.Core" />
        <PackageReference Include="Hangfire.MemoryStorage" />
        <PackageReference Include="Hangfire.PostgreSql" />
        <PackageReference Include="Hangfire.Storage.SQLite" />
        <PackageReference Include="Hangfire.SqlServer" />
        <PackageReference Include="DistributedLock"/>
        <PackageReference Include="DistributedLock.Postgres"/>
        <PackageReference Include="DistributedLock.Redis"/>
        <PackageReference Include="JetBrains.Annotations" />
		<PackageReference Include="Proto.Cluster.Kubernetes" />
		<PackageReference Include="Proto.Persistence.Sqlite" />
		<PackageReference Include="Proto.Persistence.SqlServer" />
    </ItemGroup>

	<ItemGroup>
      <Folder Include="App_Data\" />
    </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\modules\actors\Elsa.Actors.ProtoActor\Elsa.Actors.ProtoActor.csproj" />
	  <ProjectReference Include="..\..\modules\agents\Elsa.Agents.Persistence.EFCore.MySql\Elsa.Agents.Persistence.EFCore.MySql.csproj" />
	  <ProjectReference Include="..\..\modules\agents\Elsa.Agents.Persistence.EFCore.PostgreSql\Elsa.Agents.Persistence.EFCore.PostgreSql.csproj" />
	  <ProjectReference Include="..\..\modules\agents\Elsa.Agents.Persistence.EFCore.Sqlite\Elsa.Agents.Persistence.EFCore.Sqlite.csproj" />
	  <ProjectReference Include="..\..\modules\agents\Elsa.Agents.Persistence.EFCore.SqlServer\Elsa.Agents.Persistence.EFCore.SqlServer.csproj" />
	  <ProjectReference Include="..\..\modules\agents\Elsa.Agents.Persistence.EFCore\Elsa.Agents.Persistence.EFCore.csproj" />
	  <ProjectReference Include="..\..\modules\alterations\Elsa.Alterations.MassTransit\Elsa.Alterations.MassTransit.csproj" />
	  <ProjectReference Include="..\..\modules\caching\Elsa.Caching.Distributed.MassTransit\Elsa.Caching.Distributed.MassTransit.csproj" />
	  <ProjectReference Include="..\..\modules\caching\Elsa.Caching.Distributed.ProtoActor\Elsa.Caching.Distributed.ProtoActor.csproj" />
	  <ProjectReference Include="..\..\modules\connections\Elsa.Connections.Persistence.EFCore.Sqlite\Elsa.Connections.Persistence.EFCore.Sqlite.csproj" />
	  <ProjectReference Include="..\..\modules\connections\Elsa.Connections.Persistence.EFCore\Elsa.Connections.Persistence.EFCore.csproj" />
	  <ProjectReference Include="..\..\modules\diagnostics\Elsa.OpenTelemetry\Elsa.OpenTelemetry.csproj" />
	  <ProjectReference Include="..\..\modules\dropins\Elsa.DropIns\Elsa.DropIns.csproj" />
	  <ProjectReference Include="..\..\modules\email\Elsa.Email\Elsa.Email.csproj" />
	  <ProjectReference Include="..\..\modules\ldap\Elsa.Ldap\Elsa.Ldap.csproj" />
	  <ProjectReference Include="..\..\modules\mqtt\Elsa.Mqtt\Elsa.Mqtt.csproj" />
	  <ProjectReference Include="..\..\modules\persistence\Elsa.Persistence.Dapper.Migrations\Elsa.Persistence.Dapper.Migrations.csproj" />
	  <ProjectReference Include="..\..\modules\persistence\Elsa.Persistence.Dapper\Elsa.Persistence.Dapper.csproj" />
	  <ProjectReference Include="..\..\modules\persistence\Elsa.Persistence.MongoDb\Elsa.Persistence.MongoDb.csproj" />
	  <ProjectReference Include="..\..\modules\retention\Elsa.Retention\Elsa.Retention.csproj" />
	  <ProjectReference Include="..\..\modules\runtimes\Elsa.Workflows.Runtime.ProtoActor\Elsa.Workflows.Runtime.ProtoActor.csproj" />
	  <ProjectReference Include="..\..\modules\scheduling\Elsa.Scheduling.Hangfire\Elsa.Scheduling.Hangfire.csproj" />
	  <ProjectReference Include="..\..\modules\scheduling\Elsa.Scheduling.Quartz.EFCore.MySql\Elsa.Scheduling.Quartz.EFCore.MySql.csproj" />
	  <ProjectReference Include="..\..\modules\scheduling\Elsa.Scheduling.Quartz.EFCore.PostgreSql\Elsa.Scheduling.Quartz.EFCore.PostgreSql.csproj" />
	  <ProjectReference Include="..\..\modules\scheduling\Elsa.Scheduling.Quartz.EFCore.Sqlite\Elsa.Scheduling.Quartz.EFCore.Sqlite.csproj" />
	  <ProjectReference Include="..\..\modules\scheduling\Elsa.Scheduling.Quartz.EFCore.SqlServer\Elsa.Scheduling.Quartz.EFCore.SqlServer.csproj" />
	  <ProjectReference Include="..\..\modules\secrets\Elsa.Secrets.Api\Elsa.Secrets.Api.csproj" />
	  <ProjectReference Include="..\..\modules\secrets\Elsa.Secrets.Persistence.EFCore.PostgreSql\Elsa.Secrets.Persistence.EFCore.PostgreSql.csproj" />
	  <ProjectReference Include="..\..\modules\secrets\Elsa.Secrets.Persistence.EFCore.Sqlite\Elsa.Secrets.Persistence.EFCore.Sqlite.csproj" />
	  <ProjectReference Include="..\..\modules\secrets\Elsa.Secrets.Persistence.EFCore.SqlServer\Elsa.Secrets.Persistence.EFCore.SqlServer.csproj" />
	  <ProjectReference Include="..\..\modules\secrets\Elsa.Secrets.Persistence.EFCore\Elsa.Secrets.Persistence.EFCore.csproj" />
	  <ProjectReference Include="..\..\modules\secrets\Elsa.Secrets.Scripting\Elsa.Secrets.Scripting.csproj" />
	  <ProjectReference Include="..\..\modules\servicebus\Elsa.ServiceBus.Kafka\Elsa.ServiceBus.Kafka.csproj" />
	  <ProjectReference Include="..\..\modules\servicebus\Elsa.ServiceBus.MassTransit.AzureServiceBus\Elsa.ServiceBus.MassTransit.AzureServiceBus.csproj" />
	  <ProjectReference Include="..\..\modules\servicebus\Elsa.ServiceBus.MassTransit.RabbitMq\Elsa.ServiceBus.MassTransit.RabbitMq.csproj" />
	  <ProjectReference Include="..\..\modules\servicebus\Elsa.ServiceBus.MassTransit\Elsa.ServiceBus.MassTransit.csproj" />
	  <ProjectReference Include="..\..\modules\sql\Elsa.Sql.MySql\Elsa.Sql.MySql.csproj" />
	  <ProjectReference Include="..\..\modules\sql\Elsa.Sql.PostgreSql\Elsa.Sql.PostgreSql.csproj" />
	  <ProjectReference Include="..\..\modules\sql\Elsa.Sql.Sqlite\Elsa.Sql.Sqlite.csproj" />
	  <ProjectReference Include="..\..\modules\sql\Elsa.Sql.SqlServer\Elsa.Sql.SqlServer.csproj" />
	  <ProjectReference Include="..\..\modules\storage\Elsa.Storage.Files\Elsa.Storage.Files.csproj" />
	  <ProjectReference Include="..\..\modules\workflows\Elsa.WorkflowContexts\Elsa.WorkflowContexts.csproj" />
	</ItemGroup>

</Project>
