<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            Provides distributed caching services and utility functions common to Elsa modules.
        </Description>
        <PackageTags>elsa extension module caching distributed</PackageTags>
    </PropertyGroup>

    <ItemGroup Label="Elsa" Condition="'$(UseProjectReferences)' != 'true'">
        <ProjectReference Include="../../../modules/Elsa.Caching/Elsa.Caching.csproj"/>
    </ItemGroup>

    <ItemGroup Label="Elsa" Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="../../../modules/Elsa.Caching/Elsa.Caching.csproj"/>
    </ItemGroup>

</Project>
