<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <Import Project="$(MSBuildThisFileDirectory)Fody.props" />

  <PropertyGroup Label="TargetFrameworks">
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Label="Files">
    <None Include="..\..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
  </ItemGroup>

</Project>