<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><OutputType>Exe</OutputType><IsPackable>false</IsPackable><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><UseProjectReferences>true</UseProjectReferences></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../elsa-core/src/modules/Elsa/Elsa.csproj" />
    <ProjectReference Include="../elsa-extensions/src/modules/workflows/Elsa.WorkflowContexts/Elsa.WorkflowContexts.csproj" />
    <ProjectReference Include="../elsa-extensions/src/modules/workflows/Elsa.Studio.WorkflowContexts/Elsa.Studio.WorkflowContexts.csproj" />
  </ItemGroup>
</Project>
